export const ES_LEVELS = [
  { name: "Saludos", desc: "Greetings & Basics", dialect: "neutral", icon: "👋" },
  { name: "Ser y Estar", desc: "To Be (Both Ways)", dialect: "neutral", icon: "🪞" },
  { name: "La Comida", desc: "Food & Drink", dialect: "neutral", icon: "🍽️" },
  { name: "Los Números", desc: "Numbers & Counting", dialect: "neutral", icon: "🔢" },
  { name: "La Ciudad", desc: "Getting Around", dialect: "neutral", icon: "🏙️" },
  { name: "El Trabajo", desc: "Work & Daily Life", dialect: "neutral", icon: "💼" },
  { name: "El Tiempo", desc: "Weather & Time", dialect: "neutral", icon: "⛅" },
  { name: "La Familia", desc: "Family & People", dialect: "neutral", icon: "👨‍👩‍👧‍👦" },
  { name: "Verbos", desc: "Essential Verbs", dialect: "neutral", icon: "⚡" },
  { name: "Conversación", desc: "Real Conversations", dialect: "neutral", icon: "💬" },
  { name: "Boricua Basics", desc: "Caribbean Intro", dialect: "caribbean", icon: "🇵🇷" },
  { name: "Calle Style", desc: "Street Slang & Flow", dialect: "caribbean", icon: "🔥" },
];
export const ES_Q = {
  0: [
    { type:"translate",q:"Hello",a:"Hola",o:["Hola","Adiós","Gracias","Bueno"],ph:"OH-lah",ex:"The universal Spanish greeting — works any time of day." },
    { type:"translate",q:"Good morning",a:"Buenos días",o:["Buenas noches","Buenos días","Buenas tardes","Hasta luego"],ph:"BWEH-nohs DEE-ahs",ex:"'Buenos' = good, 'días' = days. Used until about noon." },
    { type:"translate",q:"How are you?",a:"¿Cómo estás?",o:["¿Cómo estás?","¿Qué hora es?","¿Dónde estás?","¿Quién eres?"],ph:"KOH-moh ehs-TAHS",ex:"'Cómo' = how, 'estás' = you are (temporary state)." },
    { type:"fillblank",q:"Buenos _____, señor.",a:"días",o:["días","noche","hola","bien"],ph:"DEE-ahs",ex:"Morning greeting. 'Noches' would be nighttime." },
    { type:"translate",q:"Goodbye",a:"Adiós",o:["Hola","Gracias","Adiós","Por favor"],ph:"ah-dee-OHS",ex:"Literally 'to God' — a formal farewell." },
    { type:"scenario",q:"You walk into a shop at 3pm. What do you say?",a:"Buenas tardes",o:["Buenos días","Buenas tardes","Buenas noches","Hola, amigo"],ph:"BWEH-nahs TAR-dehs",ex:"Afternoon (roughly noon to sundown) = 'buenas tardes'." },
    { type:"translate",q:"Thank you",a:"Gracias",o:["De nada","Por favor","Gracias","Lo siento"],ph:"GRAH-see-ahs",ex:"One of the most important words. 'Muchas gracias' = thank you very much." },
    { type:"fillblank",q:"Mucho _____ en conocerte.",a:"gusto",o:["bien","gusto","hola","grande"],ph:"GOOSE-toh",ex:"'Mucho gusto' = much pleasure. It's 'nice to meet you'." },
    { type:"translate",q:"Please",a:"Por favor",o:["Gracias","De nada","Lo siento","Por favor"],ph:"por fah-VOR",ex:"Literally 'as a favor' — always polite to add." },
    { type:"scenario",q:"Someone says 'Gracias.' How do you respond?",a:"De nada",o:["Hola","Adiós","De nada","Buenos días"],ph:"deh NAH-dah",ex:"'De nada' = of nothing. It's 'you're welcome'." },
    { type:"translate",q:"I'm sorry",a:"Lo siento",o:["Lo siento","Con permiso","De nada","Perdón"],ph:"loh see-EHN-toh",ex:"Literally 'I feel it' — used for apologies." },
    { type:"translate",q:"Excuse me",a:"Disculpe",o:["Gracias","Disculpe","Hola","Perdón"],ph:"dees-KOOL-peh",ex:"Formal way to get attention or apologize. 'Perdón' is more casual." },
    { type:"fillblank",q:"¿Cómo te _____?",a:"llamas",o:["llamas","estás","sientes","haces"],ph:"YAH-mahs",ex:"'Llamar' = to call. 'Te llamas' = you call yourself (your name)." },
    { type:"scenario",q:"You bump into someone on the street:",a:"¡Perdón! Lo siento",o:["Hola, ¿cómo estás?","¡Perdón! Lo siento","Buenos días","Adiós"],ph:"pehr-DOHN",ex:"'Perdón' for quick apology + 'lo siento' for emphasis." },
    { type:"translate",q:"My name is...",a:"Me llamo...",o:["Yo soy...","Me llamo...","Tengo...","Estoy..."],ph:"meh YAH-moh",ex:"Literally 'I call myself...' The standard way to give your name." },
    { type:"translate",q:"Nice to meet you",a:"Mucho gusto",o:["Buenas tardes","Mucho gusto","Hasta luego","Con permiso"],ph:"MOO-choh GOOSE-toh",ex:"Literally 'much pleasure.' Said when meeting someone new." },
    { type:"fillblank",q:"Hasta _____, amigo.",a:"luego",o:["mañana","luego","pronto","bien"],ph:"LWEH-goh",ex:"'Hasta luego' = until later. 'Hasta mañana' = until tomorrow." },
    { type:"scenario",q:"It's 9pm. Greet your neighbor:",a:"Buenas noches",o:["Buenos días","Buenas tardes","Buenas noches","Hola, buenos"],ph:"BWEH-nahs NOH-chehs",ex:"After sundown = 'buenas noches'. Also used to say goodnight." },
    { type:"translate",q:"See you tomorrow",a:"Hasta mañana",o:["Hasta luego","Hasta mañana","Nos vemos","Buenas noches"],ph:"AHS-tah mahn-YAH-nah",ex:"'Hasta' = until, 'mañana' = tomorrow (also means morning)." },
    { type:"fillblank",q:"Yo _____ bien, gracias.",a:"estoy",o:["soy","estoy","tengo","hago"],ph:"ehs-TOY",ex:"'Estoy' (estar) for how you feel right now. 'Soy' (ser) is for permanent traits." },
  ],
  1: [
    { type:"translate",q:"I am (permanent trait)",a:"Yo soy",o:["Yo soy","Yo estoy","Yo tengo","Yo voy"],ph:"yoh SOY",ex:"Ser = permanent things: nationality, profession, personality." },
    { type:"translate",q:"I am (temporary state)",a:"Yo estoy",o:["Yo soy","Yo estoy","Yo era","Yo fui"],ph:"yoh ehs-TOY",ex:"Estar = temporary things: mood, location, condition." },
    { type:"fillblank",q:"Yo _____ de Washington DC.",a:"soy",o:["estoy","soy","tengo","voy"],ph:"SOY",ex:"Where you're FROM = ser. Where you ARE right now = estar." },
    { type:"fillblank",q:"Yo _____ cansado hoy.",a:"estoy",o:["soy","estoy","tengo","era"],ph:"ehs-TOY",ex:"Tired is temporary → estar. You won't be tired forever." },
    { type:"scenario",q:"Tell someone where you are FROM:",a:"Soy de DC",o:["Estoy en DC","Soy de DC","Voy a DC","Tengo DC"],ph:"SOY deh",ex:"Origin = ser. 'Estoy en DC' means you're currently located there." },
    { type:"translate",q:"She is tall (permanent)",a:"Ella es alta",o:["Ella es alta","Ella está alta","Ella tiene alta","Ella va alta"],ph:"EH-yah ehs AHL-tah",ex:"Height is permanent → ser. 'Está alta' would imply she grew temporarily." },
    { type:"fillblank",q:"Nosotros _____ en la oficina.",a:"estamos",o:["somos","estamos","tenemos","vamos"],ph:"ehs-TAH-mohs",ex:"Location = estar. You're AT the office right now, not permanently." },
    { type:"translate",q:"They are students",a:"Ellos son estudiantes",o:["Ellos están estudiantes","Ellos son estudiantes","Ellos tienen estudiantes","Ellos van estudiantes"],ph:"EH-yohs sohn ehs-too-dee-AHN-tehs",ex:"Identity/role = ser. Being a student defines who they are." },
    { type:"fillblank",q:"La comida _____ deliciosa.",a:"está",o:["es","está","son","están"],ph:"ehs-TAH",ex:"The food tastes delicious RIGHT NOW → estar. It's a current experience." },
    { type:"scenario",q:"Describe your mood right now:",a:"Estoy bien",o:["Soy bien","Estoy bien","Tengo bien","Hago bien"],ph:"ehs-TOY bee-EHN",ex:"Mood = temporary → estar. 'Soy bien' doesn't work in Spanish." },
    { type:"translate",q:"He is a doctor (profession)",a:"Él es doctor",o:["Él está doctor","Él es doctor","Él tiene doctor","Él va doctor"],ph:"ehl ehs dok-TOR",ex:"Profession = identity → ser." },
    { type:"fillblank",q:"La fiesta _____ en mi casa.",a:"es",o:["es","está","son","hay"],ph:"ehs",ex:"Events use ser for location. 'The party IS at my house' = es." },
    { type:"scenario",q:"Say the coffee is hot (temporary):",a:"El café está caliente",o:["El café es caliente","El café está caliente","El café tiene caliente","El café va caliente"],ph:"ehs-TAH kah-lee-EHN-teh",ex:"Temperature is a current condition → estar." },
    { type:"translate",q:"We are happy (right now)",a:"Estamos contentos",o:["Somos contentos","Estamos contentos","Tenemos contentos","Vamos contentos"],ph:"ehs-TAH-mohs kohn-TEHN-tohs",ex:"Current emotion → estar." },
    { type:"fillblank",q:"Ella _____ muy inteligente.",a:"es",o:["es","está","tiene","va"],ph:"ehs",ex:"Intelligence is a permanent trait → ser." },
    { type:"translate",q:"The door is open (state)",a:"La puerta está abierta",o:["La puerta es abierta","La puerta está abierta","La puerta tiene abierta","La puerta va abierta"],ph:"ehs-TAH ah-bee-EHR-tah",ex:"Open/closed is a current state → estar." },
    { type:"scenario",q:"Say you are tired today:",a:"Hoy estoy cansado",o:["Hoy soy cansado","Hoy estoy cansado","Hoy tengo cansado","Hoy voy cansado"],ph:"ehs-TOY kahn-SAH-doh",ex:"Tiredness is temporary → estar." },
    { type:"fillblank",q:"¿Dónde _____ el baño?",a:"está",o:["es","está","son","hay"],ph:"ehs-TAH",ex:"Location of a physical thing → estar." },
    { type:"translate",q:"You are very kind (trait)",a:"Eres muy amable",o:["Estás muy amable","Eres muy amable","Tienes muy amable","Vas muy amable"],ph:"EH-rehs mooy ah-MAH-bleh",ex:"Kindness as a personality trait → ser." },
    { type:"fillblank",q:"Yo _____ mexicano.",a:"soy",o:["soy","estoy","tengo","hago"],ph:"SOY",ex:"Nationality is permanent → ser." },
  ],
  2: [
    { type:"translate",q:"Water",a:"Agua",o:["Leche","Agua","Jugo","Café"],ph:"AH-gwah",ex:"One of the first survival words. 'Agua, por favor' gets you far." },
    { type:"translate",q:"Chicken",a:"Pollo",o:["Cerdo","Pescado","Pollo","Carne"],ph:"POH-yoh",ex:"Most common meat in Latin American cuisine." },
    { type:"fillblank",q:"Quiero un café con _____.",a:"leche",o:["agua","arroz","leche","pollo"],ph:"LEH-cheh",ex:"'Leche' = milk. 'Café con leche' is coffee with milk." },
    { type:"scenario",q:"Ask for the check:",a:"La cuenta, por favor",o:["El menú, por favor","La cuenta, por favor","Más agua, por favor","La comida, por favor"],ph:"lah KWEHN-tah",ex:"'Cuenta' = check/bill. Essential restaurant phrase." },
    { type:"translate",q:"I'm hungry",a:"Tengo hambre",o:["Estoy hambre","Soy hambre","Tengo hambre","Quiero hambre"],ph:"TEHN-goh AHM-breh",ex:"Spanish says 'I HAVE hunger' not 'I AM hungry'. Same for thirst." },
    { type:"translate",q:"Breakfast",a:"Desayuno",o:["Almuerzo","Cena","Desayuno","Merienda"],ph:"deh-sah-YOO-noh",ex:"Literally 'un-fast' — breaking the fast. Almuerzo=lunch, Cena=dinner." },
    { type:"fillblank",q:"Me gustaría _____ el pollo.",a:"ordenar",o:["comer","ordenar","beber","cocinar"],ph:"or-deh-NAR",ex:"'Ordenar' = to order. 'Comer' = to eat. Different actions." },
    { type:"scenario",q:"Order a coffee with milk:",a:"Un café con leche, por favor",o:["Quiero agua","Un café con leche, por favor","Dame arroz","Necesito pollo"],ph:"oon kah-FEH kohn LEH-cheh",ex:"'Un' = a/one, 'con' = with. Simple and polite." },
    { type:"translate",q:"Delicious",a:"Delicioso",o:["Caliente","Frío","Delicioso","Picante"],ph:"deh-lee-see-OH-soh",ex:"Also 'rico' or 'sabroso' in casual speech." },
    { type:"translate",q:"Beer",a:"Cerveza",o:["Vino","Cerveza","Refresco","Jugo"],ph:"sehr-VEH-sah",ex:"'Una cerveza, por favor' — you'll use this one." },
    { type:"fillblank",q:"La sopa está muy _____.",a:"caliente",o:["fría","caliente","grande","buena"],ph:"kah-lee-EHN-teh",ex:"'Caliente' = hot (temperature). 'Picante' = hot (spicy)." },
    { type:"translate",q:"I'm thirsty",a:"Tengo sed",o:["Tengo hambre","Tengo sed","Estoy sed","Quiero sed"],ph:"TEHN-goh SEHD",ex:"'Tengo sed' = I have thirst. Same pattern as hunger." },
    { type:"scenario",q:"Ask what the waiter recommends:",a:"¿Qué me recomienda?",o:["¿Cuánto cuesta?","¿Qué me recomienda?","¿Dónde está el baño?","¿Tiene agua?"],ph:"keh meh reh-koh-mee-EHN-dah",ex:"Great way to discover local favorites at any restaurant." },
    { type:"translate",q:"The menu",a:"El menú",o:["La carta","El menú","La cuenta","El plato"],ph:"ehl meh-NOO",ex:"'La carta' also works for menu in some countries." },
    { type:"translate",q:"Spicy",a:"Picante",o:["Dulce","Salado","Picante","Amargo"],ph:"pee-KAHN-teh",ex:"Don't confuse with 'caliente' (hot temperature)." },
    { type:"scenario",q:"Tell the waiter you don't eat meat:",a:"No como carne",o:["No tengo hambre","No como carne","No quiero postre","No bebo alcohol"],ph:"noh KOH-moh KAR-neh",ex:"'Como' = I eat, 'carne' = meat. Direct and clear." },
    { type:"translate",q:"Dessert",a:"Postre",o:["Entrada","Postre","Plato","Bebida"],ph:"POHS-treh",ex:"'Entrada' = appetizer/starter, 'postre' = dessert." },
    { type:"translate",q:"Rice",a:"Arroz",o:["Pan","Arroz","Pollo","Carne"],ph:"ah-ROHS",ex:"Staple in Latin American cuisine. 'Arroz con pollo' = rice with chicken." },
    { type:"fillblank",q:"Quiero _____ más, por favor.",a:"pan",o:["pan","mesa","silla","cuenta"],ph:"PAHN",ex:"'Pan' = bread. 'Más' = more." },
    { type:"fillblank",q:"La _____ estuvo excelente.",a:"comida",o:["mesa","comida","cuenta","silla"],ph:"koh-MEE-dah",ex:"'Comida' = food/meal. 'Mesa' = table, 'silla' = chair." },
  ],
  // Levels 3-9 abbreviated for size — same structure with ph and ex fields
  3: [
    { type:"translate",q:"One",a:"Uno",o:["Uno","Dos","Tres","Diez"],ph:"OO-noh",ex:"The basics. Uno, dos, tres, cuatro, cinco..." },
    { type:"translate",q:"Twenty",a:"Veinte",o:["Doce","Quince","Veinte","Treinta"],ph:"VAIN-teh",ex:"11-15 are unique. 16-19 are 'dieci+number'. 20 is 'veinte'." },
    { type:"translate",q:"One hundred",a:"Cien",o:["Diez","Mil","Cien","Cincuenta"],ph:"see-EHN",ex:"'Cien' = exactly 100. 'Ciento' + number for 101-199." },
    { type:"fillblank",q:"Tengo _____ años. (35)",a:"treinta y cinco",o:["veinticinco","treinta y cinco","cuarenta","quince"],ph:"TRAIN-tah ee SEEN-koh",ex:"30+ numbers: thirty AND five. Always 'y' (and) between." },
    { type:"translate",q:"How much does it cost?",a:"¿Cuánto cuesta?",o:["¿Qué hora es?","¿Cuánto cuesta?","¿Dónde está?","¿Cuántos hay?"],ph:"KWAHN-toh KWEHS-tah",ex:"Essential shopping phrase. 'Cuánto' = how much." },
    { type:"fillblank",q:"Son _____ dólares. ($50)",a:"cincuenta",o:["quince","cincuenta","quinientos","cinco"],ph:"seen-KWEHN-tah",ex:"50 = cincuenta. 500 = quinientos. Don't mix them up." },
    { type:"translate",q:"First",a:"Primero",o:["Segundo","Primero","Último","Tercero"],ph:"pree-MEH-roh",ex:"Primero, segundo, tercero = first, second, third." },
    { type:"scenario",q:"Say 'five, five, five':",a:"Cinco, cinco, cinco",o:["Tres, tres, tres","Cinco, cinco, cinco","Seis, seis, seis","Uno, uno, uno"],ph:"SEEN-koh",ex:"Phone numbers are said digit by digit in Spanish." },
    { type:"translate",q:"Half",a:"Medio",o:["Todo","Medio","Doble","Poco"],ph:"MEH-dee-oh",ex:"'Media hora' = half hour. 'Mediodía' = noon (midday)." },
    { type:"fillblank",q:"Necesito _____ minutos. (10)",a:"diez",o:["dos","cinco","diez","veinte"],ph:"dee-EHS",ex:"Diez = 10. One of the first numbers to memorize." },
    { type:"translate",q:"Fifteen",a:"Quince",o:["Cinco","Quince","Cincuenta","Quinientos"],ph:"KEEN-seh",ex:"11-15 have unique forms: once, doce, trece, catorce, quince." },
    { type:"translate",q:"One thousand",a:"Mil",o:["Cien","Mil","Millón","Diez mil"],ph:"MEEL",ex:"'Mil' = 1,000. 'Un millón' = 1,000,000." },
    { type:"fillblank",q:"Hay _____ personas aquí. (12)",a:"doce",o:["dos","diez","doce","veinte"],ph:"DOH-seh",ex:"'Doce' = 12. 'Dos' = 2. Easy to confuse." },
    { type:"scenario",q:"Ask how many people are in line:",a:"¿Cuántas personas hay en la fila?",o:["¿Dónde está la fila?","¿Cuántas personas hay en la fila?","¿Cuánto cuesta?","¿Quién es el último?"],ph:"KWAHN-tahs pehr-SOH-nahs",ex:"'Cuántas' (feminine) matches 'personas'. 'Fila' = line/queue." },
    { type:"translate",q:"Forty",a:"Cuarenta",o:["Catorce","Cuarenta","Cuatrocientos","Cincuenta"],ph:"kwah-REHN-tah",ex:"Catorce=14, Cuarenta=40, Cuatrocientos=400. Pattern recognition." },
    { type:"translate",q:"Zero",a:"Cero",o:["Uno","Nada","Cero","Ninguno"],ph:"SEH-roh",ex:"'Nada' = nothing (noun). 'Cero' = the number zero." },
    { type:"scenario",q:"Tell a taxi: address number 1500:",a:"Número mil quinientos",o:["Número quince","Número ciento cincuenta","Número mil quinientos","Número quinientos"],ph:"NOO-meh-roh meel kee-nee-EHN-tohs",ex:"1500 = mil (1000) + quinientos (500)." },
    { type:"translate",q:"Third",a:"Tercero",o:["Primero","Segundo","Tercero","Cuarto"],ph:"tehr-SEH-roh",ex:"Ordinal numbers: primero, segundo, tercero, cuarto, quinto." },
    { type:"fillblank",q:"Somos _____ en el equipo. (6)",a:"seis",o:["tres","cinco","seis","siete"],ph:"SAYS",ex:"Seis = 6. Siete = 7. Close but different." },
    { type:"fillblank",q:"Mi dirección es el número _____. (200)",a:"doscientos",o:["veinte","doscientos","dos mil","doce"],ph:"dohs-see-EHN-tohs",ex:"200 = doscientos. 2000 = dos mil. 20 = veinte." },
  ],
  4: [
    { type:"translate",q:"Where is...?",a:"¿Dónde está...?",o:["¿Cómo está...?","¿Dónde está...?","¿Qué es...?","¿Cuándo es...?"],ph:"DOHN-deh ehs-TAH",ex:"'Dónde' = where. Uses 'estar' because location is temporary." },
    { type:"translate",q:"Turn left",a:"Doble a la izquierda",o:["Siga derecho","Doble a la izquierda","Doble a la derecha","Pare aquí"],ph:"DOH-bleh ah lah ees-kee-EHR-dah",ex:"'Doble' = turn, 'izquierda' = left, 'derecha' = right." },
    { type:"fillblank",q:"El restaurante está a la _____.",a:"derecha",o:["arriba","abajo","derecha","lejos"],ph:"deh-REH-chah",ex:"'A la derecha' = to the right. 'A la izquierda' = to the left." },
    { type:"scenario",q:"Ask where the metro is:",a:"Disculpe, ¿dónde está el metro?",o:["¿Qué hora es?","Disculpe, ¿dónde está el metro?","Quiero ir al parque","¿Cuánto cuesta?"],ph:"dees-KOOL-peh DOHN-deh ehs-TAH ehl MEH-troh",ex:"Start with 'disculpe' (excuse me) to be polite." },
    { type:"translate",q:"Go straight",a:"Siga derecho",o:["Doble aquí","Siga derecho","Pare ahora","Vaya atrás"],ph:"SEE-gah deh-REH-choh",ex:"'Siga' = continue/follow, 'derecho' = straight." },
    { type:"translate",q:"Near / Far",a:"Cerca / Lejos",o:["Grande / Pequeño","Cerca / Lejos","Arriba / Abajo","Aquí / Allá"],ph:"SEHR-kah / LEH-hohs",ex:"'Cerca de aquí' = near here. 'Lejos' = far away." },
    { type:"fillblank",q:"_____ un taxi, por favor.",a:"Necesito",o:["Quiero","Necesito","Tengo","Soy"],ph:"neh-seh-SEE-toh",ex:"'Necesito' = I need. Stronger than 'quiero' (I want)." },
    { type:"translate",q:"The store",a:"La tienda",o:["La casa","La tienda","La iglesia","La escuela"],ph:"lah tee-EHN-dah",ex:"'Tienda' = store/shop. General term for any shop." },
    { type:"scenario",q:"Tell a taxi to stop here:",a:"Pare aquí, por favor",o:["Vamos rápido","Pare aquí, por favor","Siga derecho","Doble a la derecha"],ph:"PAH-reh ah-KEE",ex:"'Pare' = stop (command). 'Aquí' = here." },
    { type:"translate",q:"Street",a:"La calle",o:["El parque","La calle","El edificio","La plaza"],ph:"lah KAH-yeh",ex:"'Calle' = street. 'Avenida' = avenue." },
    { type:"fillblank",q:"¿_____ lejos de aquí?",a:"Está",o:["Es","Está","Hay","Tiene"],ph:"ehs-TAH",ex:"Asking about distance/location = estar." },
    { type:"translate",q:"Behind",a:"Detrás",o:["Delante","Detrás","Encima","Debajo"],ph:"deh-TRAHS",ex:"'Detrás de' = behind. 'Delante de' = in front of." },
    { type:"scenario",q:"Ask how far the airport is:",a:"¿Qué tan lejos está el aeropuerto?",o:["¿Dónde está el avión?","¿Qué tan lejos está el aeropuerto?","¿Cuánto cuesta el vuelo?","¿A qué hora sale?"],ph:"keh tahn LEH-hohs ehs-TAH ehl ah-eh-roh-PWEHR-toh",ex:"'Qué tan lejos' = how far. Useful for planning travel." },
    { type:"translate",q:"Next to",a:"Al lado de",o:["Encima de","Al lado de","Debajo de","Lejos de"],ph:"ahl LAH-doh deh",ex:"'Al lado de' = at the side of. Common for giving directions." },
    { type:"fillblank",q:"El banco está _____ de la farmacia.",a:"enfrente",o:["dentro","enfrente","encima","debajo"],ph:"ehn-FREHN-teh",ex:"'Enfrente de' = in front of / across from." },
    { type:"translate",q:"Corner",a:"La esquina",o:["La calle","La esquina","La cuadra","La avenida"],ph:"lah ehs-KEE-nah",ex:"'En la esquina' = on the corner. Key for directions." },
    { type:"scenario",q:"Ask someone to repeat directions:",a:"¿Puede repetir, por favor?",o:["Más despacio","¿Puede repetir, por favor?","No entiendo","Hable más alto"],ph:"PWEH-deh reh-peh-TEER",ex:"Polite way to ask for repetition. You'll need this a lot." },
    { type:"translate",q:"Block (city)",a:"La cuadra",o:["La calle","La cuadra","El barrio","La zona"],ph:"lah KWAH-drah",ex:"'Dos cuadras' = two blocks. Standard distance measure." },
    { type:"fillblank",q:"Camine dos _____ más.",a:"cuadras",o:["calles","cuadras","metros","pasos"],ph:"KWAH-drahs",ex:"Walk two more blocks. 'Cuadras' is the standard unit." },
    { type:"translate",q:"In front of",a:"Enfrente de",o:["Detrás de","Enfrente de","Al lado de","Lejos de"],ph:"ehn-FREHN-teh deh",ex:"Also 'delante de'. Both mean in front of." },
  ],
  5: [
    { type:"translate",q:"I work in government",a:"Trabajo en el gobierno",o:["Trabajo en el gobierno","Estudio en la universidad","Vivo en la ciudad","Voy a la oficina"],ph:"trah-BAH-hoh ehn ehl goh-bee-EHR-noh",ex:"'Trabajo' = I work. 'Gobierno' = government." },
    { type:"fillblank",q:"Soy _____ de programa.",a:"gerente",o:["doctor","gerente","profesor","abogado"],ph:"heh-REHN-teh",ex:"'Gerente' = manager. Common professional title." },
    { type:"translate",q:"Meeting",a:"Reunión",o:["Oficina","Reunión","Proyecto","Equipo"],ph:"reh-oo-nee-OHN",ex:"'Tengo una reunión' = I have a meeting." },
    { type:"translate",q:"Team",a:"Equipo",o:["Grupo","Equipo","Jefe","Trabajo"],ph:"eh-KEE-poh",ex:"Also means 'equipment'. Context makes it clear." },
    { type:"scenario",q:"Introduce your job:",a:"Trabajo en el gobierno como gerente",o:["Soy estudiante","Trabajo en el gobierno como gerente","No tengo trabajo","Voy a la oficina"],ph:"KOH-moh heh-REHN-teh",ex:"'Como' = as. Natural way to describe your role." },
    { type:"fillblank",q:"Tengo una _____ a las tres.",a:"reunión",o:["comida","reunión","fiesta","clase"],ph:"reh-oo-nee-OHN",ex:"'A las tres' = at three. Meeting at 3:00." },
    { type:"translate",q:"Boss",a:"Jefe",o:["Amigo","Jefe","Compañero","Cliente"],ph:"HEH-feh",ex:"'Jefa' for female boss. 'Mi jefe' = my boss." },
    { type:"translate",q:"Project",a:"Proyecto",o:["Trabajo","Oficina","Proyecto","Problema"],ph:"proh-YEHK-toh",ex:"Same word root as English 'project'." },
    { type:"fillblank",q:"Mi _____ tiene diecinueve personas.",a:"equipo",o:["oficina","equipo","familia","clase"],ph:"eh-KEE-poh",ex:"'Mi equipo' = my team. 'Tiene' = has." },
    { type:"scenario",q:"Say you're busy:",a:"Estoy ocupado con el trabajo",o:["No tengo tiempo","Estoy ocupado con el trabajo","Voy a casa","Quiero descansar"],ph:"ehs-TOY oh-koo-PAH-doh",ex:"'Ocupado' = busy/occupied. Uses estar (temporary state)." },
    { type:"translate",q:"Schedule",a:"Horario",o:["Calendario","Horario","Reloj","Tiempo"],ph:"oh-RAH-ree-oh",ex:"'Horario' = schedule/timetable. 'Calendario' = calendar." },
    { type:"fillblank",q:"Necesito terminar este _____ hoy.",a:"proyecto",o:["reunión","proyecto","equipo","jefe"],ph:"proh-YEHK-toh",ex:"'Terminar' = to finish. 'Hoy' = today." },
    { type:"translate",q:"Email",a:"Correo electrónico",o:["Mensaje","Correo electrónico","Carta","Teléfono"],ph:"koh-REH-oh eh-lehk-TROH-nee-koh",ex:"Often shortened to just 'correo' in conversation." },
    { type:"scenario",q:"Ask what time the meeting is:",a:"¿A qué hora es la reunión?",o:["¿Dónde es la reunión?","¿A qué hora es la reunión?","¿Quién viene?","¿Por qué hay reunión?"],ph:"ah keh OH-rah ehs",ex:"'¿A qué hora?' = at what time? Very useful phrase." },
    { type:"translate",q:"Coworker",a:"Compañero de trabajo",o:["Amigo","Compañero de trabajo","Jefe","Empleado"],ph:"kohm-pahn-YEH-roh deh trah-BAH-hoh",ex:"Literally 'companion of work'. 'Colega' also works." },
    { type:"fillblank",q:"Voy a _____ a las seis.",a:"salir",o:["comer","salir","dormir","llegar"],ph:"sah-LEER",ex:"'Salir' = to leave/go out. 'Voy a salir' = I'm going to leave." },
    { type:"translate",q:"Deadline",a:"Fecha límite",o:["Hora final","Fecha límite","Día último","Tiempo final"],ph:"FEH-chah LEE-mee-teh",ex:"'Fecha' = date, 'límite' = limit. Deadline." },
    { type:"scenario",q:"Say you'll finish by Friday:",a:"Lo termino para el viernes",o:["Lo hago mañana","Lo termino para el viernes","No puedo hoy","Necesito más tiempo"],ph:"loh tehr-MEE-noh PAH-rah ehl vee-EHR-nehs",ex:"'Para' = by/for. 'Viernes' = Friday." },
    { type:"translate",q:"Salary",a:"Salario",o:["Dinero","Salario","Pago","Cuenta"],ph:"sah-LAH-ree-oh",ex:"Also 'sueldo' in everyday speech." },
    { type:"fillblank",q:"Trabajo de lunes a _____.",a:"viernes",o:["jueves","viernes","sábado","domingo"],ph:"vee-EHR-nehs",ex:"Monday through Friday: lunes, martes, miércoles, jueves, viernes." },
  ],
  6: [
    { type:"translate",q:"What time is it?",a:"¿Qué hora es?",o:["¿Qué hora es?","¿Qué día es?","¿Cuándo es?","¿Cómo estás?"],ph:"keh OH-rah ehs",ex:"Literally 'what hour is it?' Uses ser for time." },
    { type:"translate",q:"It's hot",a:"Hace calor",o:["Hace frío","Hace calor","Está lloviendo","Está nublado"],ph:"AH-seh kah-LOR",ex:"Weather uses 'hacer': hace calor, hace frío, hace sol." },
    { type:"fillblank",q:"Hoy es _____.",a:"martes",o:["enero","martes","verano","mañana"],ph:"MAR-tehs",ex:"Days of the week don't capitalize in Spanish." },
    { type:"translate",q:"Tomorrow",a:"Mañana",o:["Ayer","Hoy","Mañana","Ahora"],ph:"mahn-YAH-nah",ex:"Also means 'morning'. Context tells you which." },
    { type:"translate",q:"It's raining",a:"Está lloviendo",o:["Hace sol","Está lloviendo","Hace viento","Está nevando"],ph:"ehs-TAH yoh-vee-EHN-doh",ex:"Rain uses 'estar + gerund'. 'Llover' = to rain." },
    { type:"fillblank",q:"Son las _____ de la tarde.",a:"tres",o:["dos","tres","cinco","una"],ph:"TREHS",ex:"'Son las...' for plural hours. 'Es la una' for 1:00." },
    { type:"scenario",q:"Tell someone it's cold today:",a:"Hoy hace frío",o:["Hoy hace calor","Hoy hace frío","Hoy es bonito","Hoy está bien"],ph:"AH-seh FREE-oh",ex:"'Hace frío' = it makes cold. Spanish weather pattern." },
    { type:"translate",q:"Week",a:"Semana",o:["Día","Mes","Semana","Año"],ph:"seh-MAH-nah",ex:"'Esta semana' = this week. 'Fin de semana' = weekend." },
    { type:"translate",q:"Yesterday",a:"Ayer",o:["Hoy","Mañana","Ayer","Ahora"],ph:"ah-YEHR",ex:"Ayer = yesterday. Hoy = today. Mañana = tomorrow." },
    { type:"fillblank",q:"El _____ pasado fui al parque.",a:"domingo",o:["enero","verano","domingo","año"],ph:"doh-MEEN-goh",ex:"'Pasado' = last/past. 'El domingo pasado' = last Sunday." },
    { type:"translate",q:"Spring",a:"Primavera",o:["Verano","Primavera","Otoño","Invierno"],ph:"pree-mah-VEH-rah",ex:"Seasons: primavera, verano, otoño, invierno." },
    { type:"fillblank",q:"Hace mucho _____ afuera.",a:"viento",o:["sol","viento","agua","frío"],ph:"vee-EHN-toh",ex:"'Viento' = wind. 'Hace viento' = it's windy." },
    { type:"scenario",q:"Ask if it will rain tomorrow:",a:"¿Va a llover mañana?",o:["¿Hace frío mañana?","¿Va a llover mañana?","¿Qué hora es?","¿Es verano?"],ph:"vah ah yoh-VEHR mahn-YAH-nah",ex:"'Va a' = going to. Future with ir + a + infinitive." },
    { type:"translate",q:"Month",a:"Mes",o:["Día","Semana","Mes","Año"],ph:"MEHS",ex:"'Este mes' = this month. Months are lowercase in Spanish." },
    { type:"translate",q:"It's sunny",a:"Hace sol",o:["Hace calor","Hace sol","Está claro","Está bonito"],ph:"AH-seh SOHL",ex:"'Hace sol' = it makes sun. Standard weather expression." },
    { type:"fillblank",q:"En _____ hace mucho calor.",a:"verano",o:["invierno","verano","otoño","marzo"],ph:"veh-RAH-noh",ex:"'Verano' = summer. The hot season." },
    { type:"translate",q:"Cloudy",a:"Nublado",o:["Soleado","Nublado","Lluvioso","Ventoso"],ph:"noo-BLAH-doh",ex:"'Está nublado' = it's cloudy. Uses estar." },
    { type:"scenario",q:"Say the weather is nice:",a:"Hoy hace buen tiempo",o:["Hoy hace mal tiempo","Hoy hace buen tiempo","Está lloviendo","Hoy es frío"],ph:"AH-seh bwehn tee-EHM-poh",ex:"'Buen tiempo' = good weather. 'Mal tiempo' = bad weather." },
    { type:"translate",q:"At night",a:"En la noche",o:["En la mañana","En la tarde","En la noche","Al mediodía"],ph:"ehn lah NOH-cheh",ex:"Time of day: mañana, tarde, noche." },
    { type:"fillblank",q:"Los _____ no trabajo.",a:"sábados",o:["lunes","miércoles","viernes","sábados"],ph:"SAH-bah-dohs",ex:"'Los sábados' = on Saturdays. Plural = every Saturday." },
  ],
  7: [
    { type:"translate",q:"Mother",a:"Madre",o:["Padre","Madre","Hermana","Abuela"],ph:"MAH-dreh",ex:"Also 'mamá' casually. 'Madre' is more formal." },
    { type:"translate",q:"Brother",a:"Hermano",o:["Primo","Tío","Hermano","Hijo"],ph:"ehr-MAH-noh",ex:"'Hermana' = sister. 'Hermanos' can mean siblings." },
    { type:"fillblank",q:"Mi _____ tiene cuatro años.",a:"sobrino",o:["hermano","sobrino","abuelo","padre"],ph:"soh-BREE-noh",ex:"'Sobrino' = nephew. 'Sobrina' = niece." },
    { type:"translate",q:"Niece",a:"Sobrina",o:["Prima","Sobrina","Hija","Hermana"],ph:"soh-BREE-nah",ex:"Female version of 'sobrino'." },
    { type:"scenario",q:"Tell someone about your pets:",a:"Tengo dos perros",o:["Tengo un gato","Tengo dos perros","No tengo mascotas","Quiero un pájaro"],ph:"TEHN-goh dohs PEH-rrohs",ex:"'Perro' = dog, 'gato' = cat, 'mascota' = pet." },
    { type:"translate",q:"Grandfather",a:"Abuelo",o:["Padre","Tío","Abuelo","Primo"],ph:"ah-BWEH-loh",ex:"'Abuela' = grandmother. 'Abuelos' = grandparents." },
    { type:"translate",q:"Wife / Husband",a:"Esposa / Esposo",o:["Novia / Novio","Esposa / Esposo","Amiga / Amigo","Hermana / Hermano"],ph:"ehs-POH-sah / ehs-POH-soh",ex:"Formal. 'Mujer' (woman) and 'marido' (husband) also common." },
    { type:"translate",q:"Son / Daughter",a:"Hijo / Hija",o:["Primo / Prima","Hijo / Hija","Nieto / Nieta","Sobrino / Sobrina"],ph:"EE-hoh / EE-hah",ex:"'Hijos' = children. The 'h' is always silent in Spanish." },
    { type:"scenario",q:"Say you have a big family:",a:"Tengo una familia grande",o:["Mi familia es pequeña","Tengo una familia grande","No tengo familia","Vivo solo"],ph:"fah-MEE-lee-ah GRAHN-deh",ex:"'Grande' = big. 'Pequeña' = small." },
    { type:"fillblank",q:"Mi _____ cocina muy bien.",a:"abuela",o:["perro","abuela","carro","casa"],ph:"ah-BWEH-lah",ex:"'Cocina' = cooks/kitchen. Grandma cooks well — universal truth." },
    { type:"translate",q:"Cousin",a:"Primo",o:["Hermano","Primo","Tío","Sobrino"],ph:"PREE-moh",ex:"'Prima' = female cousin. 'Primos' = cousins." },
    { type:"translate",q:"Uncle",a:"Tío",o:["Abuelo","Primo","Tío","Padre"],ph:"TEE-oh",ex:"'Tía' = aunt. Also used as slang for 'dude' in Spain." },
    { type:"fillblank",q:"Mis _____ viven en Texas.",a:"padres",o:["amigos","padres","perros","jefes"],ph:"PAH-drehs",ex:"'Padres' = parents. 'Padre' = father." },
    { type:"scenario",q:"Introduce your sister:",a:"Ella es mi hermana",o:["Ella es mi madre","Ella es mi hermana","Ella es mi prima","Ella es mi amiga"],ph:"EH-yah ehs mee ehr-MAH-nah",ex:"Simple introduction. 'Ella es...' = she is..." },
    { type:"translate",q:"Grandchildren",a:"Nietos",o:["Hijos","Sobrinos","Nietos","Primos"],ph:"nee-EH-tohs",ex:"'Nieto' = grandson, 'nieta' = granddaughter." },
    { type:"fillblank",q:"Somos una familia muy _____.",a:"unida",o:["grande","unida","bonita","nueva"],ph:"oo-NEE-dah",ex:"'Unida' = close/united. Common way to describe family." },
    { type:"translate",q:"Girlfriend / Boyfriend",a:"Novia / Novio",o:["Esposa / Esposo","Novia / Novio","Amiga / Amigo","Mujer / Hombre"],ph:"NOH-vee-ah / NOH-vee-oh",ex:"Also means bride/groom depending on context." },
    { type:"scenario",q:"Say your nephew loves trucks:",a:"A mi sobrino le encantan los camiones",o:["Mi sobrino es grande","A mi sobrino le encantan los camiones","Tiene cuatro años","Vive conmigo"],ph:"leh ehn-KAHN-tahn lohs kah-mee-OH-nehs",ex:"'Encantar' = to love/enchant. 'Camiones' = trucks." },
    { type:"translate",q:"Twins",a:"Gemelos",o:["Hermanos","Gemelos","Primos","Amigos"],ph:"heh-MEH-lohs",ex:"'Gemelos' = twins. Also means cufflinks!" },
    { type:"fillblank",q:"Mi _____ favorita es la de Navidad.",a:"tradición",o:["comida","tradición","fiesta","familia"],ph:"trah-dee-see-OHN",ex:"'Tradición' = tradition. 'Navidad' = Christmas." },
  ],
  8: [
    { type:"translate",q:"To go",a:"Ir",o:["Ser","Ir","Ver","Dar"],ph:"EER",ex:"Irregular verb. Voy, vas, va, vamos, van." },
    { type:"translate",q:"To want",a:"Querer",o:["Poder","Querer","Deber","Saber"],ph:"keh-REHR",ex:"Stem-changing: quiero, quieres, quiere..." },
    { type:"fillblank",q:"Yo _____ ir al restaurante.",a:"quiero",o:["tengo","quiero","puedo","debo"],ph:"kee-EH-roh",ex:"'Quiero' + infinitive = I want to (do something)." },
    { type:"translate",q:"To know (a fact)",a:"Saber",o:["Conocer","Saber","Pensar","Creer"],ph:"sah-BEHR",ex:"'Saber' = know facts/how to. 'Conocer' = know people/places." },
    { type:"translate",q:"I can",a:"Yo puedo",o:["Yo quiero","Yo debo","Yo puedo","Yo sé"],ph:"yoh PWEH-doh",ex:"'Poder' = to be able to. Very useful verb." },
    { type:"fillblank",q:"Nosotros _____ al parque los domingos.",a:"vamos",o:["somos","vamos","tenemos","hacemos"],ph:"VAH-mohs",ex:"'Vamos' = we go. 'Ir a' = to go to." },
    { type:"translate",q:"To do / To make",a:"Hacer",o:["Decir","Hacer","Poner","Tener"],ph:"ah-SEHR",ex:"'Hago' = I do/make. Irregular in yo form." },
    { type:"scenario",q:"Say 'I need to work':",a:"Necesito trabajar",o:["Quiero trabajar","Necesito trabajar","Puedo trabajar","Debo trabajar"],ph:"neh-seh-SEE-toh trah-bah-HAR",ex:"'Necesitar' + infinitive = need to do something." },
    { type:"fillblank",q:"¿Tú _____ dónde está el banco?",a:"sabes",o:["conoces","sabes","quieres","puedes"],ph:"SAH-behs",ex:"'Sabes' = you know (a fact). 'Conoces' = you know (a person/place)." },
    { type:"translate",q:"To speak",a:"Hablar",o:["Escuchar","Hablar","Leer","Escribir"],ph:"ah-BLAR",ex:"Regular -ar verb. Hablo, hablas, habla, hablamos, hablan." },
    { type:"translate",q:"To eat",a:"Comer",o:["Beber","Comer","Cocinar","Pedir"],ph:"koh-MEHR",ex:"Regular -er verb. Como, comes, come, comemos, comen." },
    { type:"translate",q:"To sleep",a:"Dormir",o:["Descansar","Dormir","Soñar","Despertar"],ph:"dor-MEER",ex:"Stem-changing: duermo, duermes, duerme..." },
    { type:"fillblank",q:"Ella _____ español muy bien.",a:"habla",o:["sabe","habla","tiene","conoce"],ph:"AH-blah",ex:"'Habla' = she speaks. Regular conjugation." },
    { type:"scenario",q:"Say you don't understand:",a:"No entiendo",o:["No sé","No entiendo","No puedo","No quiero"],ph:"noh ehn-tee-EHN-doh",ex:"Essential survival phrase. Say it often while learning." },
    { type:"translate",q:"To give",a:"Dar",o:["Tomar","Dar","Poner","Traer"],ph:"DAR",ex:"Irregular: doy, das, da, damos, dan." },
    { type:"fillblank",q:"¿_____ venir conmigo?",a:"Puedes",o:["Sabes","Puedes","Quieres","Debes"],ph:"PWEH-dehs",ex:"'¿Puedes...?' = Can you...? Asking about ability." },
    { type:"translate",q:"To leave",a:"Salir",o:["Entrar","Salir","Llegar","Volver"],ph:"sah-LEER",ex:"'Salgo' = I leave (irregular yo form). 'Sales' = you leave." },
    { type:"translate",q:"To bring",a:"Traer",o:["Llevar","Traer","Dar","Poner"],ph:"trah-EHR",ex:"'Traer' = bring here. 'Llevar' = take there." },
    { type:"scenario",q:"Ask for help:",a:"¿Me puedes ayudar?",o:["¿Me puedes dar?","¿Me puedes ayudar?","¿Me puedes decir?","¿Me puedes llevar?"],ph:"meh PWEH-dehs ah-yoo-DAR",ex:"'Ayudar' = to help. Very polite way to ask." },
    { type:"fillblank",q:"Voy a _____ temprano mañana.",a:"salir",o:["dormir","salir","comer","trabajar"],ph:"sah-LEER",ex:"'Voy a salir' = I'm going to leave. Near future tense." },
  ],
  9: [
    { type:"scenario",q:"Meet someone new at a party:",a:"¡Hola! ¿Cómo te llamas?",o:["¡Adiós!","¡Hola! ¿Cómo te llamas?","¿Cuánto cuesta?","Tengo hambre"],ph:"KOH-moh teh YAH-mahs",ex:"Natural opener. 'How do you call yourself?'" },
    { type:"fillblank",q:"¿De dónde _____?",a:"eres",o:["estás","eres","tienes","vas"],ph:"EH-rehs",ex:"Asking where someone is FROM = ser (permanent)." },
    { type:"scenario",q:"Someone asks what you do:",a:"Trabajo en el gobierno. Soy gerente.",o:["No sé","Trabajo en el gobierno. Soy gerente.","Soy estudiante","No trabajo"],ph:"trah-BAH-hoh ehn ehl goh-bee-EHR-noh",ex:"Two sentences: what you do + your title. Natural flow." },
    { type:"translate",q:"I like it a lot",a:"Me gusta mucho",o:["Me gusta mucho","No me gusta","Me encanta","Está bien"],ph:"meh GOOS-tah MOO-choh",ex:"'Gustar' works backwards: 'it pleases me' = I like it." },
    { type:"fillblank",q:"¿_____ gustó la comida?",a:"Te",o:["Me","Te","Le","Se"],ph:"teh",ex:"'¿Te gustó?' = Did you like it? Past tense of gustar." },
    { type:"scenario",q:"Find the bathroom:",a:"Disculpa, ¿dónde está el baño?",o:["Necesito agua","Disculpa, ¿dónde está el baño?","Quiero irme","Estoy cansado"],ph:"DOHN-deh ehs-TAH ehl BAHN-yoh",ex:"Survival Spanish #1. 'Baño' = bathroom." },
    { type:"translate",q:"See you later",a:"Nos vemos",o:["Adiós","Hasta luego","Nos vemos","Buenas noches"],ph:"nohs VEH-mohs",ex:"Literally 'we see each other'. Casual and friendly." },
    { type:"fillblank",q:"Fue un _____ conocerte.",a:"placer",o:["gusto","placer","bueno","grande"],ph:"plah-SEHR",ex:"'Un placer' = a pleasure. Slightly more formal than 'mucho gusto'." },
    { type:"scenario",q:"Ask for their number:",a:"¿Me das tu número?",o:["¿Cómo te llamas?","¿Me das tu número?","¿Dónde vives?","¿Tienes carro?"],ph:"meh dahs too NOO-meh-roh",ex:"'¿Me das...?' = Will you give me...? Casual and direct." },
    { type:"translate",q:"Let's go!",a:"¡Vamos!",o:["¡Espera!","¡Vamos!","¡Para!","¡Corre!"],ph:"VAH-mohs",ex:"One of the most used words. Works as 'let's go' and 'come on'." },
    { type:"scenario",q:"Say you're learning Spanish:",a:"Estoy aprendiendo español",o:["Hablo español","Estoy aprendiendo español","No hablo español","Sé un poco"],ph:"ehs-TOY ah-prehn-dee-EHN-doh",ex:"Present progressive: estoy + -iendo. Shows ongoing action." },
    { type:"fillblank",q:"¿Quieres ir a _____ algo?",a:"tomar",o:["hacer","tomar","ver","dar"],ph:"toh-MAR",ex:"'Tomar algo' = to have a drink. Common social invitation." },
    { type:"translate",q:"What do you think?",a:"¿Qué piensas?",o:["¿Qué quieres?","¿Qué piensas?","¿Qué haces?","¿Qué dices?"],ph:"keh pee-EHN-sahs",ex:"'Pensar' = to think. Great conversation driver." },
    { type:"scenario",q:"Compliment someone's cooking:",a:"¡Esto está delicioso!",o:["Está bien","¡Esto está delicioso!","Tengo hambre","Quiero más"],ph:"EHS-toh ehs-TAH deh-lee-see-OH-soh",ex:"'Esto' = this. Complimenting food makes friends fast." },
    { type:"translate",q:"I agree",a:"Estoy de acuerdo",o:["Yo creo que sí","Estoy de acuerdo","Tienes razón","Claro que sí"],ph:"ehs-TOY deh ah-KWEHR-doh",ex:"Literally 'I am in agreement'. Very common phrase." },
    { type:"fillblank",q:"La pasé muy _____ anoche.",a:"bien",o:["mal","bien","grande","mucho"],ph:"bee-EHN",ex:"'La pasé bien' = I had a good time. 'Anoche' = last night." },
    { type:"scenario",q:"Say goodbye after a great time:",a:"La pasé increíble, gracias.",o:["Adiós","La pasé increíble, gracias.","Buenas noches","Hasta mañana"],ph:"lah pah-SEH een-kreh-EE-bleh",ex:"'Increíble' = incredible. Warm and genuine farewell." },
    { type:"translate",q:"Of course!",a:"¡Claro que sí!",o:["¡Tal vez!","¡Claro que sí!","¡No sé!","¡Quién sabe!"],ph:"KLAH-roh keh SEE",ex:"'Claro' = clear/of course. Emphatic agreement." },
    { type:"fillblank",q:"Vamos a _____ este fin de semana.",a:"salir",o:["trabajar","salir","dormir","estudiar"],ph:"sah-LEER",ex:"'Salir' = to go out. Weekend plans." },
    { type:"scenario",q:"Invite someone to hang out:",a:"¿Quieres salir este fin de semana?",o:["¿Tienes tiempo?","¿Quieres salir este fin de semana?","¿Vas a trabajar?","¿Dónde vives?"],ph:"kee-EH-rehs sah-LEER EHS-teh feen deh seh-MAH-nah",ex:"Direct and casual invitation. Natural way to make plans." },
  ],
  10: [
    { type:"translate",q:"What's up? (PR)",a:"¿Qué lo que?",o:["¿Cómo estás?","¿Qué tal?","¿Qué lo que?","¿Qué pasa?"],ph:"keh loh keh",ex:"Purely Caribbean. You won't hear this in Mexico." },
    { type:"translate",q:"Awesome! (PR)",a:"¡Wepa!",o:["¡Oye!","¡Wepa!","¡Mira!","¡Dale!"],ph:"WEH-pah",ex:"Puerto Rican exclamation of excitement. Like 'yay!' but cooler." },
    { type:"fillblank",q:"Esa canción está _____. (amazing)",a:"brutal",o:["buena","brutal","bonita","grande"],ph:"broo-TAHL",ex:"In Caribbean Spanish, 'brutal' = amazing/awesome. Not violent." },
    { type:"translate",q:"Let's go (Caribbean)",a:"¡Dale!",o:["¡Vamos!","¡Dale!","¡Espera!","¡Corre!"],ph:"DAH-leh",ex:"Pitbull made it famous but it's everyday Caribbean speech." },
    { type:"scenario",q:"Friend shows you great food:",a:"¡Wepa! Eso se ve brutal, mano",o:["Está bueno","¡Wepa! Eso se ve brutal, mano","Quiero comer","Gracias"],ph:"WEH-pah EH-soh seh veh broo-TAHL MAH-noh",ex:"Stacking slang: wepa (wow) + brutal (amazing) + mano (bro)." },
    { type:"translate",q:"Dude / Bro (PR)",a:"Mano",o:["Amigo","Hermano","Mano","Señor"],ph:"MAH-noh",ex:"Short for 'hermano'. Universal Caribbean bro term." },
    { type:"fillblank",q:"Estoy más cansao que un _____.",a:"perro",o:["gato","perro","niño","viejo"],ph:"PEH-rroh",ex:"Caribbean exaggeration. 'More tired than a dog.' Note: 'cansao' drops the 'd' from 'cansado'." },
    { type:"translate",q:"Don't mess with me (PR)",a:"No me jodas",o:["Déjame en paz","No me jodas","No me hables","Vete de aquí"],ph:"noh meh HOH-dahs",ex:"Informal/vulgar. Only with close friends. Strong language." },
    { type:"scenario",q:"Greet your PR friend casually:",a:"¡Qué lo que, pana! ¿Cómo andas?",o:["Buenos días, señor","¡Qué lo que, pana! ¿Cómo andas?","Hola, ¿cómo estás?","¿Qué tal?"],ph:"keh loh keh PAH-nah KOH-moh AHN-dahs",ex:"Full Caribbean greeting: 'what's up, buddy, how you doing?'" },
    { type:"translate",q:"That's a mess (PR)",a:"¡Qué relajo!",o:["¡Qué problema!","¡Qué relajo!","¡Qué lío!","¡Qué horror!"],ph:"keh reh-LAH-hoh",ex:"'Relajo' = mess/chaos/disorder. Very Puerto Rican." },
    { type:"fillblank",q:"Todo bien, gracias a _____.",a:"Dios",o:["ti","Dios","todos","mí"],ph:"dee-OHS",ex:"'Gracias a Dios' = thank God. Very common Caribbean response." },
    { type:"translate",q:"Buddy (PR)",a:"Pana",o:["Amigo","Pana","Mano","Compa"],ph:"PAH-nah",ex:"Puerto Rican for friend/buddy. 'Mano' and 'pana' are interchangeable." },
    { type:"scenario",q:"React to surprising news PR style:",a:"¡No me digas! ¿De verdad?",o:["¿En serio?","¡No me digas! ¿De verdad?","Wow","Interesante"],ph:"noh meh DEE-gahs deh vehr-DAHD",ex:"'No me digas' = don't tell me! Classic PR reaction." },
    { type:"translate",q:"Everything chill",a:"Todo tranquilo",o:["Todo bien","Todo tranquilo","Todo bueno","Todo normal"],ph:"TOH-doh trahn-KEE-loh",ex:"Caribbean chill. 'Todo tranqui' is even more casual." },
    { type:"fillblank",q:"Eso está bien _____.",a:"cabrón",o:["bueno","cabrón","loco","fuerte"],ph:"kah-BROHN",ex:"Vulgar but common. Means 'crazy good' in this context. Use with friends only." },
    { type:"translate",q:"The thing is...",a:"Es que...",o:["Mira...","Es que...","Bueno...","O sea..."],ph:"ehs keh",ex:"The #1 filler phrase. Natural way to explain or excuse." },
    { type:"scenario",q:"Party was amazing. Tell your friend:",a:"¡Mano, la fiesta estuvo brutal! ¡Wepa!",o:["Estuvo bien","¡Mano, la fiesta estuvo brutal! ¡Wepa!","Me gustó","Fue divertido"],ph:"MAH-noh lah fee-EHS-tah ehs-TOO-voh broo-TAHL WEH-pah",ex:"Full Caribbean hype. 'Estuvo' = it was (estar, past tense)." },
    { type:"translate",q:"Dang! (PR)",a:"¡Diache!",o:["¡Caramba!","¡Diache!","¡Ay!","¡Oye!"],ph:"dee-AH-cheh",ex:"Clean exclamation. Puerto Rican version of 'damn'." },
    { type:"fillblank",q:"Vamos a janguear este _____.",a:"fin de semana",o:["día","fin de semana","momento","rato"],ph:"hahn-geh-AHR",ex:"'Janguear' comes from English 'hang out'. Spanglish at its finest." },
    { type:"translate",q:"To hang out (PR)",a:"Janguear",o:["Salir","Janguear","Pasear","Caminar"],ph:"hahn-geh-AHR",ex:"Borrowed from English. Only used in Caribbean Spanish." },
  ],
  11: [
    { type:"translate",q:"You're messing with me (PR)",a:"Me estás gufando",o:["Me estás mintiendo","Me estás gufando","Me estás molestando","Me estás hablando"],ph:"meh ehs-TAHS goo-FAHN-doh",ex:"'Gufar' = to joke/mess around. Puerto Rican slang." },
    { type:"fillblank",q:"Tengo _____ años esperando.",a:"mil",o:["diez","cien","mil","muchos"],ph:"MEEL",ex:"Caribbean exaggeration. 'I've been waiting a thousand years.'" },
    { type:"translate",q:"That song is a hit",a:"Esa canción está pegá",o:["Es buena","Esa canción está pegá","Me gusta","Es nueva"],ph:"ehs-TAH peh-GAH",ex:"'Pegá' = stuck/hit. Dropped 'd' from 'pegada' — classic Caribbean." },
    { type:"scenario",q:"Friend is late. React Caribbean:",a:"¡Mano, tengo mil años esperando!",o:["Llegas tarde","¡Mano, tengo mil años esperando!","No importa","Está bien"],ph:"TEHN-goh meel AHN-yohs",ex:"Dramatic exaggeration is a Caribbean art form." },
    { type:"fillblank",q:"El tráfico estaba al _____.",a:"garete",o:["máximo","garete","fuego","diablo"],ph:"gah-REH-teh",ex:"'Al garete' = out of control. Pure Puerto Rican expression." },
    { type:"translate",q:"Play that song (PR)",a:"Ponme esa canción",o:["Escucha esa canción","Ponme esa canción","Canta esa canción","Busca esa canción"],ph:"POHN-meh EH-sah kahn-see-OHN",ex:"'Ponme' = put on for me. Direct and casual." },
    { type:"translate",q:"Part of the crew",a:"Parte del corillo",o:["Parte del grupo","Parte del corillo","Parte del equipo","Parte del barrio"],ph:"PAR-teh dehl koh-REE-yoh",ex:"'Corillo' = crew/squad. Your inner circle." },
    { type:"scenario",q:"Hype up friend's cooking:",a:"¡Diache! Cocinas con sazón",o:["Está bueno","¡Diache! Cocinas con sazón","Gracias","Me gusta"],ph:"dee-AH-cheh koh-SEE-nahs kohn sah-SOHN",ex:"'Sazón' = seasoning/flavor. Highest cooking compliment." },
    { type:"fillblank",q:"Mira el _____ que tiene este tipo.",a:"show",o:["problema","show","relajo","drama"],ph:"SHOH",ex:"Borrowed English word. 'Look at the spectacle this guy is making.'" },
    { type:"translate",q:"Out of control (PR)",a:"Al garete",o:["Al máximo","Al garete","Al fuego","Al diablo"],ph:"ahl gah-REH-teh",ex:"Nautical origin — a ship drifting without control." },
    { type:"scenario",q:"Joke about your Spanish:",a:"Mi español es un desastre, pero aquí estamos",o:["Hablo bien","Mi español es un desastre, pero aquí estamos","No sé nada","Estoy aprendiendo"],ph:"oon deh-SAHS-treh PEH-roh ah-KEE ehs-TAH-mohs",ex:"Self-deprecating humor = the Caribbean way to connect." },
    { type:"fillblank",q:"Bad Bunny es _____.",a:"brutal",o:["bueno","brutal","famoso","grande"],ph:"broo-TAHL",ex:"Using 'brutal' to describe Bad Bunny is peak Caribbean." },
    { type:"translate",q:"Seasoning / Flavor",a:"Sazón",o:["Sal","Sazón","Sabor","Salsa"],ph:"sah-SOHN",ex:"'Sazón' = the magic touch in cooking. Also a metaphor for style." },
    { type:"scenario",q:"Traffic was insane:",a:"¡El tráfico estaba al garete!",o:["Había tráfico","¡El tráfico estaba al garete!","Estaba mal","No pude llegar"],ph:"ehl TRAH-fee-koh ehs-TAH-bah ahl gah-REH-teh",ex:"'Estaba' = it was (ongoing past). Perfect for complaining." },
    { type:"fillblank",q:"¿Dónde tú _____ anoche?",a:"estabas",o:["eras","estabas","fuiste","ibas"],ph:"ehs-TAH-bahs",ex:"Caribbean word order: '¿Dónde tú estabas?' instead of '¿Dónde estabas tú?'" },
    { type:"translate",q:"I'm dying of hunger",a:"Me muero de hambre",o:["Tengo hambre","Me muero de hambre","Quiero comer","Necesito comida"],ph:"meh MWEH-roh deh AHM-breh",ex:"Dramatic exaggeration. You're not actually dying. Probably." },
    { type:"translate",q:"Look at this spectacle!",a:"¡Mira el show!",o:["¡Mira esto!","¡Mira el show!","¡Mira allá!","¡Mira quién llegó!"],ph:"MEE-rah ehl SHOH",ex:"English loanword 'show' used in Caribbean Spanish." },
    { type:"scenario",q:"Confirm you're coming, PR style:",a:"¡Dale! Llego en un ratito",o:["Sí, voy","¡Dale! Llego en un ratito","Está bien","Voy para allá"],ph:"DAH-leh YEH-goh ehn oon rah-TEE-toh",ex:"'Dale' = do it/let's go. 'Ratito' = a little while (diminutive)." },
    { type:"fillblank",q:"Ahora eres parte del _____.",a:"corillo",o:["grupo","corillo","equipo","barrio"],ph:"koh-REE-yoh",ex:"Welcome to the crew. You've arrived." },
    { type:"translate",q:"A little while",a:"Un ratito",o:["Un momento","Un ratito","Un segundo","Un rato"],ph:"oon rah-TEE-toh",ex:"Diminutive of 'rato'. Could mean 5 min or 2 hours — Caribbean time." },
  ],
};
