// FRENCH QUESTIONS — 10 levels, 20 questions each
// Phonetics use approximate English sounds
// Explanations teach grammar/culture context

export const FR_LEVELS = [
  { name: "L'Alphabet", desc: "Sounds & Pronunciation", dialect: "neutral", icon: "🔤" },
  { name: "Salutations", desc: "Greetings & Basics", dialect: "neutral", icon: "👋" },
  { name: "La Nourriture", desc: "Food & Drink", dialect: "neutral", icon: "🍽️" },
  { name: "Les Nombres", desc: "Numbers & Counting", dialect: "neutral", icon: "🔢" },
  { name: "La Ville", desc: "Getting Around", dialect: "neutral", icon: "🏙️" },
  { name: "Le Travail", desc: "Work & Daily Life", dialect: "neutral", icon: "💼" },
  { name: "Le Temps", desc: "Weather & Time", dialect: "neutral", icon: "⛅" },
  { name: "La Famille", desc: "Family & People", dialect: "neutral", icon: "👨‍👩‍👧‍👦" },
  { name: "Les Verbes", desc: "Essential Verbs", dialect: "neutral", icon: "⚡" },
  { name: "Conversation", desc: "Real Conversations", dialect: "neutral", icon: "💬" },
];

export const FR_Q = {
  0: [
    { type:"translate",q:"The French 'r' sounds like...",a:"A gargle in the back of the throat",o:["A gargle in the back of the throat","A rolled 'r' like Spanish","Same as English 'r'","Silent"],ph:"r = throat gargle",ex:"The French R is uvular — produced at the back of the throat, not with the tongue." },
    { type:"translate",q:"The 'u' in French sounds like...",a:"'oo' with tight lips pushed forward",o:["'oo' as in 'food'","'uh' as in 'up'","'oo' with tight lips pushed forward","'you' as in 'youth'"],ph:"u = tight-lipped 'oo'",ex:"No English equivalent. Say 'ee' but round your lips tightly." },
    { type:"translate",q:"The nasal 'on' sounds like...",a:"'oh' through your nose",o:["'on' as in English","'oh' through your nose","'oon' like 'moon'","'un' like 'fun'"],ph:"on = nasalized 'oh'",ex:"French has nasal vowels: on, an, in, un. Air goes through the nose." },
    { type:"translate",q:"The 'oi' combination sounds like...",a:"'wah'",o:["'oy'","'wah'","'oh-ee'","'aw'"],ph:"oi = wah",ex:"'Moi' = mwah. 'Toi' = twah. 'Boire' = bwahr." },
    { type:"fillblank",q:"In French, the last consonant of a word is usually _____.",a:"silent",o:["stressed","silent","doubled","soft"],ph:"n/a",ex:"'Petit' = puh-TEE (t is silent). 'Grands' = GRAH (d and s silent)." },
    { type:"translate",q:"The 'é' sounds like...",a:"'ay' as in 'say'",o:["'ee' as in 'see'","'ay' as in 'say'","'eh' as in 'bed'","'uh' as in 'the'"],ph:"é = ay",ex:"'Café' = kah-FAY. The accent tells you it's a clean 'ay' sound." },
    { type:"translate",q:"The 'è' sounds like...",a:"'eh' as in 'bed'",o:["'ay' as in 'say'","'ee' as in 'see'","'eh' as in 'bed'","'uh' as in 'up'"],ph:"è = eh",ex:"'Père' = pehr. Open sound, like English 'bed'." },
    { type:"translate",q:"The 'eau' combination sounds like...",a:"'oh'",o:["'ow'","'oh'","'oo'","'aw'"],ph:"eau = oh",ex:"'Beau' = BOH. 'Eau' = OH (water). Three letters, one sound." },
    { type:"fillblank",q:"'Ch' in French sounds like _____ in English.",a:"'sh'",o:["'ch'","'sh'","'k'","'tch'"],ph:"ch = sh",ex:"'Chat' (cat) = SHAH. Never hard like English 'church'." },
    { type:"translate",q:"The letter 'j' in French sounds like...",a:"'zh' as in 'measure'",o:["'j' as in 'jump'","'zh' as in 'measure'","'y' as in 'yes'","'h' as in 'hat'"],ph:"j = zh",ex:"'Je' = ZHUH. 'Bonjour' = boh-ZHOOR." },
    { type:"translate",q:"The nasal 'an' sounds like...",a:"'ah' through your nose",o:["'an' as in English","'ah' through your nose","'on' through your nose","'en' like 'hen'"],ph:"an = nasalized 'ah'",ex:"'France' = FRAHS (nasal). Don't pronounce the n." },
    { type:"translate",q:"How do you pronounce 'qu'?",a:"'k'",o:["'kw'","'k'","'kyoo'","'gw'"],ph:"qu = k",ex:"'Qui' = KEE. 'Que' = KUH. No 'w' sound like English." },
    { type:"fillblank",q:"The word 'oui' (yes) is pronounced _____.",a:"'wee'",o:["'oo-ee'","'wee'","'oy'","'way'"],ph:"wee",ex:"Two letters but sounds like English 'we'. The most important word!" },
    { type:"translate",q:"The 'gn' combination sounds like...",a:"'ny' as in 'canyon'",o:["'gn' as in 'gnome'","'ny' as in 'canyon'","'n' as in 'no'","'ng' as in 'sing'"],ph:"gn = ny",ex:"'Montagne' (mountain) = moh-TAHN-yuh." },
    { type:"scenario",q:"You see 'Bonjour'. How do you say it?",a:"boh-ZHOOR",o:["BON-joor","boh-ZHOOR","boh-JOR","BON-zhoor"],ph:"boh-ZHOOR",ex:"Stress is on the last syllable. The 'j' is soft like 'measure'." },
    { type:"translate",q:"The 'ille' ending sounds like...",a:"'ee-yuh'",o:["'ill'","'ee-yuh'","'eel'","'eye'"],ph:"ille = ee-yuh",ex:"'Fille' (girl) = FEE-yuh. 'Famille' = fah-MEE-yuh." },
    { type:"fillblank",q:"French has _____ grammatical genders.",a:"two",o:["one","two","three","four"],ph:"n/a",ex:"Masculine (le) and feminine (la). You have to memorize which." },
    { type:"translate",q:"The 'eu' sound is like...",a:"'uh' with rounded lips",o:["'oo'","'uh' with rounded lips","'ew'","'ay-oo'"],ph:"eu = rounded 'uh'",ex:"'Bleu' = BLUH (with rounded lips). 'Peu' = PUH." },
    { type:"scenario",q:"You see 'Merci beaucoup'. Break it down:",a:"mehr-SEE boh-KOO",o:["MER-see BOW-coop","mehr-SEE boh-KOO","MER-chee boh-COOP","mehr-KI boh-KOO"],ph:"mehr-SEE boh-KOO",ex:"Thank you very much. 'Beaucoup' = boh-KOO (p is silent)." },
    { type:"translate",q:"Liaison means...",a:"Linking a final consonant to the next vowel",o:["Dropping a consonant","Linking a final consonant to the next vowel","Adding a pause","Changing a vowel"],ph:"n/a",ex:"'Les amis' = lay-zah-MEE. The 's' links to the vowel." },
  ],
  1: [
    { type:"translate",q:"Hello (formal)",a:"Bonjour",o:["Bonjour","Au revoir","Merci","Bonsoir"],ph:"boh-ZHOOR",ex:"Literally 'good day'. Used until evening. THE essential word." },
    { type:"translate",q:"Hello (casual)",a:"Salut",o:["Salut","Au revoir","Merci","Bonjour"],ph:"sah-LOO",ex:"Casual hi/bye with friends. Never use with strangers." },
    { type:"translate",q:"Good evening",a:"Bonsoir",o:["Bonjour","Bonsoir","Bonne nuit","Salut"],ph:"boh-SWAHR",ex:"Used after about 6pm. Switch from 'bonjour' to 'bonsoir'." },
    { type:"fillblank",q:"_____, comment allez-vous?",a:"Bonjour",o:["Bonjour","Merci","Au revoir","Salut"],ph:"boh-ZHOOR koh-mah tah-lay VOO",ex:"Formal greeting + 'how are you?' Always start conversations this way in France." },
    { type:"translate",q:"Goodbye",a:"Au revoir",o:["Bonjour","Merci","Au revoir","Bonsoir"],ph:"oh ruh-VWAHR",ex:"Literally 'until seeing again'. Formal farewell." },
    { type:"scenario",q:"You walk into a bakery. What do you say first?",a:"Bonjour!",o:["Merci!","Bonjour!","Au revoir!","Salut!"],ph:"boh-ZHOOR",ex:"ALWAYS say bonjour when entering a shop in France. Not saying it is considered rude." },
    { type:"translate",q:"Thank you",a:"Merci",o:["Pardon","S'il vous plaît","Merci","De rien"],ph:"mehr-SEE",ex:"'Merci beaucoup' = thank you very much." },
    { type:"translate",q:"Please",a:"S'il vous plaît",o:["Merci","De rien","Pardon","S'il vous plaît"],ph:"seel voo PLEH",ex:"Literally 'if it pleases you'. Essential politeness." },
    { type:"fillblank",q:"Je m'_____ Marie.",a:"appelle",o:["suis","appelle","ai","fais"],ph:"zhuh mah-PEL",ex:"'Je m'appelle' = I call myself. Standard self-introduction." },
    { type:"scenario",q:"Someone holds the door. You say:",a:"Merci!",o:["Pardon!","Merci!","Bonjour!","Au revoir!"],ph:"mehr-SEE",ex:"Quick thanks. Short and sweet." },
    { type:"translate",q:"Yes / No",a:"Oui / Non",o:["Oui / Non","Si / No","Ja / Nein","Da / Net"],ph:"WEE / NOH",ex:"'Oui' = wee. 'Non' = noh (nasal). The basics." },
    { type:"translate",q:"Excuse me",a:"Excusez-moi",o:["Excusez-moi","Merci","S'il vous plaît","Bonjour"],ph:"ex-koo-zay MWAH",ex:"Also 'pardon' for bumping into someone." },
    { type:"translate",q:"You're welcome",a:"De rien",o:["Merci","De rien","S'il vous plaît","Pardon"],ph:"duh ree-EH",ex:"Literally 'of nothing'. Casual. 'Je vous en prie' is more formal." },
    { type:"fillblank",q:"Comment _____-vous?",a:"allez",o:["êtes","allez","avez","faites"],ph:"koh-mah tah-lay VOO",ex:"'Comment allez-vous?' = How are you going? (formal)." },
    { type:"scenario",q:"It's 8pm. Greet someone:",a:"Bonsoir!",o:["Bonjour!","Bonsoir!","Salut!","Bonne nuit!"],ph:"boh-SWAHR",ex:"Evening greeting. 'Bonne nuit' = goodnight (only when going to bed)." },
    { type:"translate",q:"I don't understand",a:"Je ne comprends pas",o:["Je ne sais pas","Je ne comprends pas","Je ne parle pas","Je ne peux pas"],ph:"zhuh nuh koh-PRAH pah",ex:"Survival phrase #1. The 'ne...pas' wraps around the verb." },
    { type:"translate",q:"Nice to meet you",a:"Enchanté",o:["Bonjour","Enchanté","Au revoir","Merci"],ph:"ah-shah-TAY",ex:"Literally 'enchanted'. Men say 'enchanté', women 'enchantée' (sounds the same)." },
    { type:"fillblank",q:"Je suis _____ bien, merci.",a:"très",o:["beaucoup","très","aussi","plus"],ph:"TREH",ex:"'Très' = very. 'Je suis très bien' = I'm very well." },
    { type:"translate",q:"I'm sorry",a:"Je suis désolé",o:["Je suis désolé","Excusez-moi","Pardon","Merci"],ph:"zhuh swee day-zoh-LAY",ex:"For genuine apologies. 'Pardon' for minor things." },
    { type:"scenario",q:"Meet someone new. Introduce yourself:",a:"Bonjour, je m'appelle... Enchanté!",o:["Au revoir!","Bonjour, je m'appelle... Enchanté!","Bonne nuit!","Merci beaucoup!"],ph:"zhuh mah-PEL... ah-shah-TAY",ex:"Greeting + name + pleased to meet you. The French trifecta." },
  ],
  2: [
    { type:"translate",q:"Water",a:"L'eau",o:["Le lait","L'eau","Le jus","Le café"],ph:"LOH",ex:"'Eau' = oh. With the article: l'eau. One of the first survival words." },
    { type:"translate",q:"Bread",a:"Le pain",o:["Le pain","Le riz","La viande","Le fromage"],ph:"luh PAH",ex:"France and bread — inseparable. 'Une baguette' is the iconic loaf." },
    { type:"fillblank",q:"Je voudrais un _____, s'il vous plaît.",a:"café",o:["café","table","chaise","assiette"],ph:"kah-FAY",ex:"'Je voudrais' = I would like. The polite way to order anything." },
    { type:"scenario",q:"Order a beer:",a:"Une bière, s'il vous plaît",o:["Un café, s'il vous plaît","Une bière, s'il vous plaît","De l'eau, s'il vous plaît","L'addition, s'il vous plaît"],ph:"oon bee-EHR seel voo PLEH",ex:"'Une' because 'bière' is feminine. Gender matters for articles." },
    { type:"translate",q:"I'm hungry",a:"J'ai faim",o:["Je suis faim","J'ai faim","Je veux faim","Je fais faim"],ph:"zhay FAH",ex:"French says 'I HAVE hunger' not 'I AM hungry'. Same as Spanish." },
    { type:"translate",q:"Breakfast",a:"Le petit-déjeuner",o:["Le déjeuner","Le petit-déjeuner","Le dîner","Le goûter"],ph:"luh puh-TEE day-zhuh-NAY",ex:"Literally 'the small lunch'. Déjeuner=lunch, dîner=dinner." },
    { type:"translate",q:"Chicken",a:"Le poulet",o:["Le porc","Le poulet","Le bœuf","Le poisson"],ph:"luh poo-LEH",ex:"'Poulet rôti' = roast chicken. Classic French comfort food." },
    { type:"fillblank",q:"La soupe est très _____.",a:"chaude",o:["froide","chaude","grande","bonne"],ph:"SHOHD",ex:"'Chaud/chaude' = hot. 'Froid/froide' = cold." },
    { type:"scenario",q:"Ask for the check:",a:"L'addition, s'il vous plaît",o:["Le menu, s'il vous plaît","L'addition, s'il vous plaît","Plus d'eau, s'il vous plaît","Le plat, s'il vous plaît"],ph:"lah-dee-see-OH seel voo PLEH",ex:"'Addition' = the bill. Essential restaurant phrase." },
    { type:"translate",q:"Delicious",a:"Délicieux",o:["Chaud","Froid","Délicieux","Épicé"],ph:"day-lee-see-UH",ex:"'C'est délicieux!' = It's delicious! High compliment." },
    { type:"translate",q:"I'm thirsty",a:"J'ai soif",o:["J'ai faim","J'ai soif","Je suis soif","Je veux soif"],ph:"zhay SWAHF",ex:"Same 'avoir' (have) pattern: j'ai faim, j'ai soif." },
    { type:"fillblank",q:"Je voudrais _____ le poulet.",a:"commander",o:["manger","commander","boire","cuisiner"],ph:"koh-mah-DAY",ex:"'Commander' = to order. 'Manger' = to eat." },
    { type:"translate",q:"The menu",a:"La carte",o:["L'addition","La carte","Le plat","Le verre"],ph:"lah KART",ex:"'La carte' = the menu. 'Le menu' exists but means a fixed-price meal." },
    { type:"scenario",q:"Say you don't eat meat:",a:"Je ne mange pas de viande",o:["Je n'ai pas faim","Je ne mange pas de viande","Je ne veux pas de dessert","Je ne bois pas d'alcool"],ph:"zhuh nuh MAHNZH pah duh vee-AHND",ex:"'Ne...pas' negation around the verb. 'Viande' = meat." },
    { type:"translate",q:"Cheese",a:"Le fromage",o:["Le pain","Le fromage","Le beurre","La saucisse"],ph:"luh froh-MAHZH",ex:"France has 400+ varieties of cheese. They take it seriously." },
    { type:"translate",q:"Wine",a:"Le vin",o:["La bière","Le vin","Le jus","L'eau"],ph:"luh VAH",ex:"'Vin rouge' = red wine. 'Vin blanc' = white wine." },
    { type:"fillblank",q:"Est-ce que je peux voir la _____?",a:"carte",o:["addition","carte","cuisine","toilette"],ph:"lah KART",ex:"'Est-ce que je peux...' = May I... Very polite." },
    { type:"translate",q:"Spicy",a:"Épicé",o:["Sucré","Salé","Épicé","Amer"],ph:"ay-pee-SAY",ex:"French food is rarely spicy. But the word exists!" },
    { type:"scenario",q:"Compliment the food:",a:"C'est vraiment délicieux!",o:["C'est bon","C'est vraiment délicieux!","J'ai faim","Encore, s'il vous plaît"],ph:"say vreh-MAH day-lee-see-UH",ex:"'Vraiment' = really/truly. Adds emphasis." },
    { type:"translate",q:"Dessert",a:"Le dessert",o:["L'entrée","Le dessert","Le plat","La boisson"],ph:"luh deh-ZEHR",ex:"Same word as English. 'L'entrée' = starter (NOT main course like in English)." },
  ],
  3: [
    { type:"translate",q:"One",a:"Un",o:["Un","Deux","Trois","Dix"],ph:"UH",ex:"French numbers: un, deux, trois, quatre, cinq..." },
    { type:"translate",q:"Twenty",a:"Vingt",o:["Douze","Quinze","Vingt","Trente"],ph:"VAH",ex:"The 'gt' is silent. Just 'vah'." },
    { type:"translate",q:"One hundred",a:"Cent",o:["Dix","Mille","Cent","Cinquante"],ph:"SAH",ex:"'Cent' = 100. 'Mille' = 1000." },
    { type:"fillblank",q:"J'ai _____ ans. (35)",a:"trente-cinq",o:["vingt-cinq","trente-cinq","quarante","quinze"],ph:"TRAHT-SAHK",ex:"30-69 are straightforward: trente-cinq = thirty-five." },
    { type:"translate",q:"How much does it cost?",a:"Combien ça coûte?",o:["Quelle heure est-il?","Combien ça coûte?","Où est-ce?","Combien y a-t-il?"],ph:"koh-bee-EH sah KOOT",ex:"'Combien' = how much/many. Essential shopping word." },
    { type:"fillblank",q:"Ça coûte _____ euros. (€50)",a:"cinquante",o:["quinze","cinquante","cinq cents","cinq"],ph:"sah-KAHNT",ex:"50 = cinquante. 500 = cinq cents. 15 = quinze." },
    { type:"translate",q:"First",a:"Premier",o:["Deuxième","Premier","Dernier","Troisième"],ph:"pruh-mee-AY",ex:"Premier, deuxième, troisième = first, second, third." },
    { type:"scenario",q:"Say 'five, five, five':",a:"Cinq, cinq, cinq",o:["Trois, trois, trois","Cinq, cinq, cinq","Six, six, six","Un, un, un"],ph:"SAHK SAHK SAHK",ex:"Phone numbers are said digit by digit or in pairs." },
    { type:"translate",q:"Half",a:"Demi",o:["Tout","Demi","Double","Peu"],ph:"duh-MEE",ex:"'Une demi-heure' = half an hour." },
    { type:"fillblank",q:"J'ai besoin de _____ minutes. (10)",a:"dix",o:["deux","cinq","dix","vingt"],ph:"DEES",ex:"Dix = 10. The 'x' is silent except before a vowel." },
    { type:"translate",q:"Seventy",a:"Soixante-dix",o:["Soixante","Soixante-dix","Septante","Sept"],ph:"swah-SAHNT DEES",ex:"Literally 'sixty-ten'! French math gets weird at 70. Belgium/Switzerland say 'septante'." },
    { type:"translate",q:"Eighty",a:"Quatre-vingts",o:["Huitante","Quatre-vingts","Huit-dix","Octante"],ph:"KAH-truh VAH",ex:"Literally 'four twenties'! 80 = 4×20. French counting is wild." },
    { type:"translate",q:"Ninety",a:"Quatre-vingt-dix",o:["Neuvante","Quatre-vingt-dix","Neuf-dix","Nonante"],ph:"KAH-truh vah DEES",ex:"'Four-twenty-ten' = 90. Yes, really. 4×20+10." },
    { type:"fillblank",q:"Il y a _____ personnes ici. (12)",a:"douze",o:["deux","dix","douze","vingt"],ph:"DOOZ",ex:"'Il y a' = there are. 'Douze' = 12." },
    { type:"scenario",q:"Ask how many people are in line:",a:"Combien de personnes dans la file?",o:["Où est la file?","Combien de personnes dans la file?","Combien ça coûte?","Qui est le dernier?"],ph:"koh-bee-EH duh pehr-SOHN dah lah FEEL",ex:"'Combien de' = how many. 'File' = line/queue." },
    { type:"translate",q:"Forty",a:"Quarante",o:["Quatorze","Quarante","Quatre cents","Cinquante"],ph:"kah-RAHNT",ex:"Quatorze=14, Quarante=40, Quatre cents=400." },
    { type:"translate",q:"Zero",a:"Zéro",o:["Un","Rien","Zéro","Aucun"],ph:"zay-ROH",ex:"Same as English. Used for phone numbers and scores." },
    { type:"scenario",q:"Tell a taxi: address number 1500:",a:"Numéro mille cinq cents",o:["Numéro quinze","Numéro cent cinquante","Numéro mille cinq cents","Numéro cinq cents"],ph:"noo-may-ROH meel SAHK SAH",ex:"1500 = mille (1000) + cinq cents (500)." },
    { type:"translate",q:"Third",a:"Troisième",o:["Premier","Deuxième","Troisième","Quatrième"],ph:"trwah-zee-EHM",ex:"Add '-ième' to make ordinals. Except 'premier' (first)." },
    { type:"fillblank",q:"Nous sommes _____ dans l'équipe. (6)",a:"six",o:["trois","cinq","six","sept"],ph:"SEES",ex:"Six = 6. 'X' pronounced as 'S' here." },
  ],
  4: [
    { type:"translate",q:"Where is...?",a:"Où est...?",o:["Comment est...?","Où est...?","Qu'est-ce que...?","Quand est...?"],ph:"oo EH",ex:"'Où' = where. Short and essential." },
    { type:"translate",q:"Turn left",a:"Tournez à gauche",o:["Allez tout droit","Tournez à gauche","Tournez à droite","Arrêtez ici"],ph:"toor-NAY ah GOHSH",ex:"'Gauche' = left, 'droite' = right." },
    { type:"fillblank",q:"Le restaurant est à _____.",a:"droite",o:["dessus","dessous","droite","loin"],ph:"DRWAHT",ex:"'À droite' = to the right. 'À gauche' = to the left." },
    { type:"scenario",q:"Ask where the metro is:",a:"Excusez-moi, où est le métro?",o:["Quelle heure est-il?","Excusez-moi, où est le métro?","Je voudrais aller au parc","Combien coûte le taxi?"],ph:"oo eh luh may-TROH",ex:"Paris metro is essential. Always start with 'excusez-moi'." },
    { type:"translate",q:"Go straight",a:"Allez tout droit",o:["Tournez ici","Allez tout droit","Arrêtez maintenant","Reculez"],ph:"ah-LAY too DRWAH",ex:"'Tout droit' = straight ahead." },
    { type:"translate",q:"Near / Far",a:"Près / Loin",o:["Grand / Petit","Près / Loin","Dessus / Dessous","Ici / Là-bas"],ph:"PREH / LWAH",ex:"'Près d'ici' = near here. 'Loin' = far." },
    { type:"fillblank",q:"J'ai _____ d'un taxi, s'il vous plaît.",a:"besoin",o:["envie","besoin","peur","hâte"],ph:"buh-ZWAH",ex:"'J'ai besoin de' = I need. Uses 'avoir' (have)." },
    { type:"translate",q:"The store",a:"Le magasin",o:["La maison","Le magasin","L'église","L'école"],ph:"luh mah-gah-ZAH",ex:"Also 'la boutique' for smaller/fancier shops." },
    { type:"scenario",q:"Tell a taxi to stop here:",a:"Arrêtez ici, s'il vous plaît",o:["Plus vite","Arrêtez ici, s'il vous plaît","Tout droit","Tournez à droite"],ph:"ah-reh-TAY ee-SEE",ex:"'Arrêtez' = stop (formal command). 'Ici' = here." },
    { type:"translate",q:"Street",a:"La rue",o:["Le parc","La rue","Le bâtiment","La place"],ph:"lah ROO",ex:"'Rue' = street. 'Avenue' and 'boulevard' also used." },
    { type:"fillblank",q:"C'est _____ d'ici?",a:"loin",o:["ici","loin","près","bien"],ph:"LWAH",ex:"'C'est loin d'ici?' = Is it far from here?" },
    { type:"translate",q:"Behind",a:"Derrière",o:["Devant","Derrière","Au-dessus","En dessous"],ph:"deh-ree-EHR",ex:"'Derrière' = behind. 'Devant' = in front." },
    { type:"scenario",q:"Ask how far the airport is:",a:"L'aéroport est loin d'ici?",o:["Où est l'avion?","L'aéroport est loin d'ici?","Combien coûte le vol?","À quelle heure part le vol?"],ph:"lah-ay-roh-POR eh LWAH dee-SEE",ex:"Simple question structure. No need for complex grammar." },
    { type:"translate",q:"Next to",a:"À côté de",o:["Au-dessus de","À côté de","En dessous de","Loin de"],ph:"ah koh-TAY duh",ex:"'À côté de la banque' = next to the bank." },
    { type:"fillblank",q:"La banque est _____ de la pharmacie.",a:"en face",o:["dedans","en face","au-dessus","en dessous"],ph:"ah FAHS",ex:"'En face de' = across from / facing." },
    { type:"translate",q:"Corner",a:"Le coin",o:["La rue","Le coin","Le bloc","L'avenue"],ph:"luh KWAH",ex:"'Au coin de la rue' = at the street corner." },
    { type:"scenario",q:"Ask someone to repeat:",a:"Pouvez-vous répéter, s'il vous plaît?",o:["Plus lentement","Pouvez-vous répéter, s'il vous plaît?","Je ne comprends pas","Parlez plus fort"],ph:"poo-vay VOO ray-pay-TAY",ex:"Very polite request. You'll need this constantly in France." },
    { type:"translate",q:"Block",a:"Le pâté de maisons",o:["La rue","Le pâté de maisons","Le quartier","La zone"],ph:"luh pah-TAY duh meh-ZOH",ex:"Literally 'block of houses'. More commonly just give street names." },
    { type:"fillblank",q:"Continuez pendant deux _____.",a:"rues",o:["coins","rues","mètres","pas"],ph:"ROO",ex:"'Continuez pendant deux rues' = continue for two streets." },
    { type:"translate",q:"In front of",a:"Devant",o:["Derrière","Devant","À côté de","Loin de"],ph:"duh-VAH",ex:"'Devant le bâtiment' = in front of the building." },
  ],
  5: [
    { type:"translate",q:"I work in government",a:"Je travaille dans le gouvernement",o:["Je travaille dans le gouvernement","J'étudie à l'université","J'habite en ville","Je vais au bureau"],ph:"zhuh trah-VY dah luh goo-vehr-nuh-MAH",ex:"'Travailler' = to work. 'Gouvernement' = government." },
    { type:"fillblank",q:"Je suis _____ de programme.",a:"directeur",o:["médecin","directeur","professeur","avocat"],ph:"dee-rehk-TUHR",ex:"'Directeur/directrice' = director/manager." },
    { type:"translate",q:"Meeting",a:"La réunion",o:["Le bureau","La réunion","Le projet","L'équipe"],ph:"lah ray-oon-ee-OH",ex:"'J'ai une réunion' = I have a meeting." },
    { type:"translate",q:"Team",a:"L'équipe",o:["Le groupe","L'équipe","Le chef","Le travail"],ph:"lay-KEEP",ex:"Same word used in sports and work." },
    { type:"scenario",q:"Introduce your job:",a:"Je travaille dans le gouvernement comme directeur",o:["Je suis étudiant","Je travaille dans le gouvernement comme directeur","Je n'ai pas de travail","Je vais au bureau"],ph:"kohm dee-rehk-TUHR",ex:"'Comme' = as. Natural job description." },
    { type:"fillblank",q:"J'ai une _____ à trois heures.",a:"réunion",o:["repas","réunion","fête","classe"],ph:"ray-oon-ee-OH",ex:"'À trois heures' = at three o'clock." },
    { type:"translate",q:"Boss",a:"Le chef",o:["L'ami","Le chef","Le collègue","Le client"],ph:"luh SHEF",ex:"Same word as in English kitchen hierarchy. 'La cheffe' = female boss." },
    { type:"translate",q:"Project",a:"Le projet",o:["Le travail","Le bureau","Le projet","Le problème"],ph:"luh proh-ZHAY",ex:"'Projet' with the soft French 'j' sound." },
    { type:"fillblank",q:"Mon _____ a dix-neuf personnes.",a:"équipe",o:["bureau","équipe","famille","classe"],ph:"ay-KEEP",ex:"'Mon équipe' = my team." },
    { type:"scenario",q:"Say you're busy:",a:"Je suis occupé avec le travail",o:["Je n'ai pas le temps","Je suis occupé avec le travail","Je rentre chez moi","Je veux me reposer"],ph:"zhuh swee oh-koo-PAY",ex:"'Occupé' = busy. Same root as English 'occupied'." },
    { type:"translate",q:"Schedule",a:"L'emploi du temps",o:["Le calendrier","L'emploi du temps","L'horloge","Le temps"],ph:"lahm-PLWAH doo TAH",ex:"Literally 'use of time'. Also 'le planning' (borrowed from English)." },
    { type:"fillblank",q:"Je dois finir ce _____ aujourd'hui.",a:"projet",o:["réunion","projet","équipe","chef"],ph:"proh-ZHAY oh-zhoor-DWEE",ex:"'Je dois' = I must. 'Aujourd'hui' = today." },
    { type:"translate",q:"Email",a:"Le courriel",o:["Le message","Le courriel","La lettre","Le téléphone"],ph:"luh koo-ree-EL",ex:"Official French word. Most people just say 'email' or 'mail'." },
    { type:"scenario",q:"Ask what time the meeting is:",a:"La réunion est à quelle heure?",o:["La réunion est où?","La réunion est à quelle heure?","Qui vient à la réunion?","Pourquoi il y a une réunion?"],ph:"ah kel UHR",ex:"'À quelle heure?' = at what time?" },
    { type:"translate",q:"Coworker",a:"Le collègue",o:["L'ami","Le collègue","Le chef","L'employé"],ph:"luh koh-LEG",ex:"'Collègue' works for male and female." },
    { type:"fillblank",q:"Je pars à _____ heures.",a:"six",o:["manger","six","dormir","arriver"],ph:"SEES",ex:"'Partir' = to leave. 'Je pars' = I'm leaving." },
    { type:"translate",q:"Deadline",a:"La date limite",o:["L'heure finale","La date limite","Le dernier jour","La fin du temps"],ph:"lah daht lee-MEET",ex:"Same structure as Spanish: 'date' + 'limit'." },
    { type:"scenario",q:"Say you'll finish by Friday:",a:"Je finis avant vendredi",o:["Je le fais demain","Je finis avant vendredi","Je ne peux pas aujourd'hui","J'ai besoin de plus de temps"],ph:"zhuh fee-NEE ah-VAH vah-druh-DEE",ex:"'Avant' = before/by. 'Vendredi' = Friday." },
    { type:"translate",q:"Salary",a:"Le salaire",o:["L'argent","Le salaire","Le paiement","La facture"],ph:"luh sah-LEHR",ex:"Same root as English 'salary'." },
    { type:"fillblank",q:"Je travaille du lundi au _____.",a:"vendredi",o:["jeudi","vendredi","samedi","dimanche"],ph:"vah-druh-DEE",ex:"Lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche." },
  ],
  6: [
    { type:"translate",q:"What time is it?",a:"Quelle heure est-il?",o:["Quelle heure est-il?","Quel jour est-ce?","Quand est-ce?","Comment allez-vous?"],ph:"kel UHR eh-TEEL",ex:"Literally 'what hour is it?' The standard way." },
    { type:"translate",q:"It's hot",a:"Il fait chaud",o:["Il fait froid","Il fait chaud","Il pleut","Il fait nuageux"],ph:"eel feh SHOH",ex:"Weather uses 'il fait': il fait chaud, il fait froid." },
    { type:"fillblank",q:"Aujourd'hui c'est _____.",a:"mardi",o:["janvier","mardi","été","demain"],ph:"mar-DEE",ex:"Days are lowercase in French, like Spanish." },
    { type:"translate",q:"Tomorrow",a:"Demain",o:["Hier","Aujourd'hui","Demain","Maintenant"],ph:"duh-MAH",ex:"Hier = yesterday. Aujourd'hui = today. Demain = tomorrow." },
    { type:"translate",q:"It's raining",a:"Il pleut",o:["Il fait soleil","Il pleut","Il fait du vent","Il neige"],ph:"eel PLUH",ex:"'Pleuvoir' = to rain. 'Il pleut' = it rains." },
    { type:"fillblank",q:"Il est _____ heures de l'après-midi. (3:00)",a:"trois",o:["deux","trois","cinq","une"],ph:"TRWAH",ex:"'De l'après-midi' = in the afternoon." },
    { type:"scenario",q:"Tell someone it's cold today:",a:"Aujourd'hui il fait froid",o:["Il fait chaud","Aujourd'hui il fait froid","Il fait beau","Il fait bon"],ph:"eel feh FRWAH",ex:"'Froid' = cold. The 'd' is silent." },
    { type:"translate",q:"Week",a:"La semaine",o:["Le jour","Le mois","La semaine","L'année"],ph:"lah suh-MEN",ex:"'Cette semaine' = this week. 'Le week-end' = weekend (borrowed from English)." },
    { type:"translate",q:"Yesterday",a:"Hier",o:["Aujourd'hui","Demain","Hier","Maintenant"],ph:"ee-EHR",ex:"The 'h' is silent. Sounds like 'ee-air'." },
    { type:"fillblank",q:"_____ dernier je suis allé au parc.",a:"Dimanche",o:["Janvier","Été","Dimanche","An"],ph:"dee-MAHNSH",ex:"'Dernier' = last. 'Dimanche dernier' = last Sunday." },
    { type:"translate",q:"Spring",a:"Le printemps",o:["L'été","Le printemps","L'automne","L'hiver"],ph:"luh prah-TAH",ex:"Seasons: printemps, été, automne, hiver." },
    { type:"fillblank",q:"Il fait beaucoup de _____ dehors.",a:"vent",o:["soleil","vent","pluie","froid"],ph:"VAH",ex:"'Vent' = wind. 'Il fait du vent' = it's windy." },
    { type:"scenario",q:"Ask if it will rain tomorrow:",a:"Est-ce qu'il va pleuvoir demain?",o:["Il fait froid demain?","Est-ce qu'il va pleuvoir demain?","Quelle heure est-il?","C'est l'été?"],ph:"ehs keel vah pluh-VWAHR duh-MAH",ex:"'Est-ce que' + future with 'aller'. Natural question form." },
    { type:"translate",q:"Month",a:"Le mois",o:["Le jour","La semaine","Le mois","L'année"],ph:"luh MWAH",ex:"'Ce mois-ci' = this month." },
    { type:"translate",q:"It's sunny",a:"Il fait soleil",o:["Il fait chaud","Il fait soleil","Il fait clair","Il fait beau"],ph:"eel feh soh-LAY",ex:"Also 'il fait beau' = the weather is nice (general)." },
    { type:"fillblank",q:"En _____ il fait très chaud.",a:"été",o:["hiver","été","automne","mars"],ph:"ay-TAY",ex:"'En été' = in summer." },
    { type:"translate",q:"Cloudy",a:"Nuageux",o:["Ensoleillé","Nuageux","Pluvieux","Venteux"],ph:"noo-ah-ZHUH",ex:"'Il fait nuageux' = it's cloudy. From 'nuage' (cloud)." },
    { type:"scenario",q:"Say the weather is nice:",a:"Il fait beau aujourd'hui",o:["Il fait mauvais","Il fait beau aujourd'hui","Il pleut","Il fait froid"],ph:"eel feh BOH oh-zhoor-DWEE",ex:"'Beau' = nice/beautiful. The all-purpose good weather word." },
    { type:"translate",q:"At night",a:"La nuit",o:["Le matin","L'après-midi","La nuit","Le midi"],ph:"lah NWEE",ex:"Time of day: matin, après-midi, soir, nuit." },
    { type:"fillblank",q:"Le _____ je ne travaille pas.",a:"samedi",o:["lundi","mercredi","vendredi","samedi"],ph:"sahm-DEE",ex:"'Le samedi' = on Saturdays." },
  ],
  7: [
    { type:"translate",q:"Mother",a:"La mère",o:["Le père","La mère","La sœur","La grand-mère"],ph:"lah MEHR",ex:"Also 'maman' casually. 'Mère' is more formal." },
    { type:"translate",q:"Brother",a:"Le frère",o:["Le cousin","L'oncle","Le frère","Le fils"],ph:"luh FREHR",ex:"'Sœur' = sister. 'Frères et sœurs' = siblings." },
    { type:"fillblank",q:"Mon _____ a quatre ans.",a:"neveu",o:["frère","neveu","grand-père","père"],ph:"nuh-VUH",ex:"'Neveu' = nephew. 'Nièce' = niece." },
    { type:"translate",q:"Niece",a:"La nièce",o:["La cousine","La nièce","La fille","La sœur"],ph:"lah nee-EHS",ex:"Female version of 'neveu'." },
    { type:"scenario",q:"Tell someone about your pets:",a:"J'ai deux chiens",o:["J'ai un chat","J'ai deux chiens","Je n'ai pas d'animaux","Je voudrais un oiseau"],ph:"zhay duh shee-EH",ex:"'Chien' = dog. 'Chat' = cat. 'Animal de compagnie' = pet." },
    { type:"translate",q:"Grandfather",a:"Le grand-père",o:["Le père","L'oncle","Le grand-père","Le cousin"],ph:"luh grah-PEHR",ex:"'Grand-mère' = grandmother. 'Grands-parents' = grandparents." },
    { type:"translate",q:"Wife / Husband",a:"La femme / Le mari",o:["La copine / Le copain","La femme / Le mari","L'amie / L'ami","La sœur / Le frère"],ph:"lah FAM / luh mah-REE",ex:"'Femme' also means 'woman'. Context makes it clear." },
    { type:"translate",q:"Son / Daughter",a:"Le fils / La fille",o:["Le cousin / La cousine","Le fils / La fille","Le petit-fils / La petite-fille","Le neveu / La nièce"],ph:"luh FEES / lah FEE-yuh",ex:"'Enfants' = children. 'Fils' — the 's' is pronounced!" },
    { type:"scenario",q:"Say you have a big family:",a:"J'ai une grande famille",o:["Ma famille est petite","J'ai une grande famille","Je n'ai pas de famille","J'habite seul"],ph:"zhay oon GRAHND fah-MEE-yuh",ex:"'Grande' = big. 'Petite' = small." },
    { type:"fillblank",q:"Ma _____ cuisine très bien.",a:"grand-mère",o:["chien","grand-mère","voiture","maison"],ph:"grah-MEHR",ex:"'Cuisiner' = to cook. Grandma cooks well — universal truth." },
    { type:"translate",q:"Cousin (male)",a:"Le cousin",o:["Le frère","Le cousin","L'oncle","Le neveu"],ph:"luh koo-ZAH",ex:"'Cousine' = female cousin." },
    { type:"translate",q:"Uncle",a:"L'oncle",o:["Le grand-père","Le cousin","L'oncle","Le père"],ph:"LOHNK-luh",ex:"'Tante' = aunt." },
    { type:"fillblank",q:"Mes _____ habitent au Texas.",a:"parents",o:["amis","parents","chiens","chefs"],ph:"pah-RAH",ex:"'Parents' = parents. 'Père' = father, 'mère' = mother." },
    { type:"scenario",q:"Introduce your sister:",a:"C'est ma sœur",o:["C'est ma mère","C'est ma sœur","C'est ma cousine","C'est mon amie"],ph:"say mah SUHR",ex:"'C'est...' = this is... Simple introduction." },
    { type:"translate",q:"Grandchildren",a:"Les petits-enfants",o:["Les enfants","Les neveux","Les petits-enfants","Les cousins"],ph:"lay puh-tee zah-FAH",ex:"Literally 'small children'. 'Petit-fils' = grandson." },
    { type:"fillblank",q:"Nous sommes une famille très _____.",a:"unie",o:["grande","unie","belle","nouvelle"],ph:"oo-NEE",ex:"'Unie' = close/united." },
    { type:"translate",q:"Girlfriend / Boyfriend",a:"La copine / Le copain",o:["La femme / Le mari","La copine / Le copain","L'amie / L'ami","La sœur / Le frère"],ph:"lah koh-PEEN / luh koh-PAH",ex:"Also 'petite amie / petit ami' (literally small friend)." },
    { type:"scenario",q:"Say your nephew loves trucks:",a:"Mon neveu adore les camions",o:["Mon neveu est grand","Mon neveu adore les camions","Il a quatre ans","Il habite avec moi"],ph:"moh nuh-VUH ah-DOR lay kah-mee-OH",ex:"'Adorer' = to love/adore. 'Camion' = truck." },
    { type:"translate",q:"Twins",a:"Les jumeaux",o:["Les frères","Les jumeaux","Les cousins","Les amis"],ph:"lay zhoo-MOH",ex:"'Jumelles' = female twins or binoculars!" },
    { type:"fillblank",q:"Ma _____ préférée c'est Noël.",a:"tradition",o:["repas","tradition","fête","famille"],ph:"trah-dee-see-OH",ex:"'Tradition' = tradition. 'Noël' = Christmas." },
  ],
  8: [
    { type:"translate",q:"To go",a:"Aller",o:["Être","Aller","Voir","Donner"],ph:"ah-LAY",ex:"Irregular: je vais, tu vas, il va, nous allons, ils vont." },
    { type:"translate",q:"To want",a:"Vouloir",o:["Pouvoir","Vouloir","Devoir","Savoir"],ph:"voo-LWAHR",ex:"'Je veux' = I want. 'Je voudrais' = I would like (politer)." },
    { type:"fillblank",q:"Je _____ aller au restaurant.",a:"veux",o:["ai","veux","peux","dois"],ph:"VUH",ex:"'Vouloir' + infinitive = to want to do something." },
    { type:"translate",q:"To know (a fact)",a:"Savoir",o:["Connaître","Savoir","Penser","Croire"],ph:"sah-VWAHR",ex:"'Savoir' = know facts/how to. 'Connaître' = know people/places." },
    { type:"translate",q:"I can",a:"Je peux",o:["Je veux","Je dois","Je peux","Je sais"],ph:"zhuh PUH",ex:"'Pouvoir' = to be able to. 'Je peux' = I can." },
    { type:"fillblank",q:"Nous _____ au parc le dimanche.",a:"allons",o:["sommes","allons","avons","faisons"],ph:"ah-LOH",ex:"'Nous allons' = we go. Irregular verb 'aller'." },
    { type:"translate",q:"To do / To make",a:"Faire",o:["Dire","Faire","Mettre","Avoir"],ph:"FEHR",ex:"'Qu'est-ce que tu fais?' = What are you doing?" },
    { type:"scenario",q:"Say 'I need to work':",a:"Je dois travailler",o:["Je veux travailler","Je dois travailler","Je peux travailler","Je devrais travailler"],ph:"zhuh DWAH trah-vy-AY",ex:"'Devoir' = must/have to. 'Je dois' = I must." },
    { type:"fillblank",q:"Tu _____ où est la banque?",a:"sais",o:["connais","sais","veux","peux"],ph:"SAY",ex:"'Tu sais?' = Do you know? (a fact). 'Tu connais?' = Do you know? (a person)." },
    { type:"translate",q:"To speak",a:"Parler",o:["Écouter","Parler","Lire","Écrire"],ph:"par-LAY",ex:"'Parlez-vous anglais?' = Do you speak English? Essential phrase." },
    { type:"translate",q:"To eat",a:"Manger",o:["Boire","Manger","Cuisiner","Commander"],ph:"mah-ZHAY",ex:"Regular -er verb. Je mange, tu manges, il mange." },
    { type:"translate",q:"To sleep",a:"Dormir",o:["Se reposer","Dormir","Rêver","Se réveiller"],ph:"dor-MEER",ex:"'Je dors' = I sleep. Irregular: dors, dors, dort, dormons." },
    { type:"fillblank",q:"Elle _____ très bien français.",a:"parle",o:["sait","parle","a","connaît"],ph:"PARL",ex:"'Parle' = speaks. Regular -er conjugation." },
    { type:"scenario",q:"Say you don't understand:",a:"Je ne comprends pas",o:["Je ne sais pas","Je ne comprends pas","Je ne peux pas","Je ne veux pas"],ph:"zhuh nuh koh-PRAH pah",ex:"'Ne...pas' wraps around the verb. Your #1 survival phrase." },
    { type:"translate",q:"To give",a:"Donner",o:["Prendre","Donner","Mettre","Apporter"],ph:"doh-NAY",ex:"'Donnez-moi...' = Give me..." },
    { type:"fillblank",q:"Tu _____ venir avec moi?",a:"peux",o:["sais","peux","veux","dois"],ph:"PUH",ex:"'Tu peux...?' = Can you...?" },
    { type:"translate",q:"To leave",a:"Partir",o:["Entrer","Partir","Arriver","Revenir"],ph:"par-TEER",ex:"'Je pars' = I'm leaving. Irregular." },
    { type:"translate",q:"To bring",a:"Apporter",o:["Emporter","Apporter","Donner","Mettre"],ph:"ah-por-TAY",ex:"'Apporter' = bring here. 'Emporter' = take away." },
    { type:"scenario",q:"Ask for help:",a:"Pouvez-vous m'aider?",o:["Pouvez-vous me donner?","Pouvez-vous m'aider?","Pouvez-vous me dire?","Pouvez-vous m'emmener?"],ph:"poo-vay VOO may-DAY",ex:"'Aider' = to help. Formal and polite." },
    { type:"fillblank",q:"Je vais _____ tôt demain.",a:"partir",o:["dormir","partir","manger","travailler"],ph:"par-TEER",ex:"'Je vais partir' = I'm going to leave. Near future." },
  ],
  9: [
    { type:"scenario",q:"Meet someone new at a party:",a:"Bonjour! Comment vous appelez-vous?",o:["Au revoir!","Bonjour! Comment vous appelez-vous?","Combien ça coûte?","J'ai faim"],ph:"koh-MAH voo zah-play VOO",ex:"Formal. 'Comment tu t'appelles?' for casual." },
    { type:"fillblank",q:"D'où _____-vous?",a:"venez",o:["êtes","venez","avez","allez"],ph:"vuh-NAY",ex:"'D'où venez-vous?' = Where do you come from?" },
    { type:"scenario",q:"Someone asks what you do:",a:"Je travaille dans le gouvernement comme directeur.",o:["Je ne sais pas","Je travaille dans le gouvernement comme directeur.","Je suis étudiant","Je ne travaille pas"],ph:"zhuh trah-VY dah luh goo-vehr-nuh-MAH",ex:"Clean professional introduction." },
    { type:"translate",q:"I like it a lot",a:"Ça me plaît beaucoup",o:["Ça me plaît beaucoup","Ça ne me plaît pas","J'adore","C'est bien"],ph:"sah muh PLEH boh-KOO",ex:"'Plaire' = to please. 'Ça me plaît' = it pleases me." },
    { type:"fillblank",q:"_____ avez aimé le repas?",a:"Vous",o:["Je","Vous","Il","Nous"],ph:"VOO",ex:"'Vous avez aimé?' = Did you enjoy? Past tense with 'avoir'." },
    { type:"scenario",q:"Find the bathroom:",a:"Excusez-moi, où sont les toilettes?",o:["J'ai besoin d'eau","Excusez-moi, où sont les toilettes?","Je voudrais partir","Je suis fatigué"],ph:"oo SOH lay twah-LET",ex:"Always plural in French: 'les toilettes'. Never singular." },
    { type:"translate",q:"See you later",a:"À plus tard",o:["Au revoir","À bientôt","À plus tard","Bonne nuit"],ph:"ah ploo TAR",ex:"Casual. 'À bientôt' = see you soon. 'À plus' = see ya." },
    { type:"fillblank",q:"C'était un _____ de vous rencontrer.",a:"plaisir",o:["bonheur","plaisir","moment","honneur"],ph:"pleh-ZEER",ex:"'Un plaisir' = a pleasure. Classic polite farewell." },
    { type:"scenario",q:"Ask for their number:",a:"Je peux avoir votre numéro?",o:["Comment vous appelez-vous?","Je peux avoir votre numéro?","Où habitez-vous?","Vous avez une voiture?"],ph:"zhuh puh ah-VWAHR voh-truh noo-may-ROH",ex:"'Votre' = your (formal). Polite way to ask." },
    { type:"translate",q:"Let's go!",a:"Allons-y!",o:["Attendez!","Allons-y!","Arrêtez!","Vite!"],ph:"ah-LOH-ZEE",ex:"The 'y' means 'there'. Very natural and common." },
    { type:"scenario",q:"Say you're learning French:",a:"J'apprends le français",o:["Je parle français","J'apprends le français","Je ne parle pas français","Je sais un peu"],ph:"zhah-PRAH luh frah-SAY",ex:"'Apprendre' = to learn. Simple and honest." },
    { type:"fillblank",q:"On va _____ un verre?",a:"prendre",o:["faire","prendre","voir","donner"],ph:"PRAH-druh",ex:"'Prendre un verre' = to have a drink. Classic French social invitation." },
    { type:"translate",q:"What do you think?",a:"Qu'est-ce que vous en pensez?",o:["Qu'est-ce que vous voulez?","Qu'est-ce que vous en pensez?","Qu'est-ce que vous faites?","Qu'est-ce que vous dites?"],ph:"kehs kuh voo zah pah-SAY",ex:"'Penser' = to think. Good conversation driver." },
    { type:"scenario",q:"Compliment someone's cooking:",a:"C'est vraiment délicieux!",o:["C'est bon","C'est vraiment délicieux!","J'ai faim","J'en veux plus"],ph:"say vreh-MAH day-lee-see-UH",ex:"'Vraiment' = truly. Strongest food compliment." },
    { type:"translate",q:"I agree",a:"Je suis d'accord",o:["Je crois que oui","Je suis d'accord","Vous avez raison","Bien sûr"],ph:"zhuh swee dah-KOR",ex:"Literally 'I am of agreement'. Very common." },
    { type:"fillblank",q:"J'ai passé une très bonne _____.",a:"soirée",o:["mal","soirée","grand","beaucoup"],ph:"swah-RAY",ex:"'Soirée' = evening. 'Bonne soirée' = nice evening." },
    { type:"scenario",q:"Say goodbye after a great time:",a:"C'était super, merci!",o:["Au revoir","C'était super, merci!","Bonne nuit","À demain"],ph:"say-TEH soo-PEHR mehr-SEE",ex:"'C'était' = it was. 'Super' = great (borrowed from English)." },
    { type:"translate",q:"Of course!",a:"Bien sûr!",o:["Peut-être!","Bien sûr!","Je ne sais pas!","Qui sait!"],ph:"bee-EH SOOR",ex:"Literally 'well sure'. Emphatic agreement." },
    { type:"fillblank",q:"On fait quelque chose ce _____?",a:"week-end",o:["travail","week-end","moment","soir"],ph:"wee-KEHND",ex:"French borrowed 'week-end' from English." },
    { type:"scenario",q:"Invite someone to hang out:",a:"Tu es libre ce week-end?",o:["Tu as du travail?","Tu es libre ce week-end?","Tu vas travailler?","Tu habites où?"],ph:"too ay LEE-bruh suh wee-KEHND",ex:"'Libre' = free (available). Casual invitation." },
  ],
};
