// MANDARIN CHINESE QUESTIONS — 10 levels, 20 questions each
// Phonetics use Pinyin with tone numbers
// Characters included in answers
// Explanations teach grammar/culture context

export const ZH_LEVELS = [
  { name: "拼音 Pīnyīn", desc: "Sounds & Tones", dialect: "neutral", icon: "🔤" },
  { name: "你好 Nǐ hǎo", desc: "Greetings & Basics", dialect: "neutral", icon: "👋" },
  { name: "吃饭 Chīfàn", desc: "Food & Drink", dialect: "neutral", icon: "🍽️" },
  { name: "数字 Shùzì", desc: "Numbers & Counting", dialect: "neutral", icon: "🔢" },
  { name: "城市 Chéngshì", desc: "Getting Around", dialect: "neutral", icon: "🏙️" },
  { name: "工作 Gōngzuò", desc: "Work & Daily Life", dialect: "neutral", icon: "💼" },
  { name: "天气 Tiānqì", desc: "Weather & Time", dialect: "neutral", icon: "⛅" },
  { name: "家人 Jiārén", desc: "Family & People", dialect: "neutral", icon: "👨‍👩‍👧‍👦" },
  { name: "动词 Dòngcí", desc: "Essential Verbs", dialect: "neutral", icon: "⚡" },
  { name: "对话 Duìhuà", desc: "Real Conversations", dialect: "neutral", icon: "💬" },
];

export const ZH_Q = {
  0: [
    { type:"translate",q:"Mandarin has how many tones?",a:"Four (plus a neutral tone)",o:["Two","Four (plus a neutral tone)","Six","Three"],ph:"4 tones + neutral",ex:"Tones change meaning completely. 'Mā' (mom) vs 'mǎ' (horse) vs 'mà' (scold)." },
    { type:"translate",q:"First tone (ā) sounds like...",a:"High and flat, like singing a note",o:["Rising like a question","High and flat, like singing a note","Falling sharply","Dipping down then up"],ph:"1st tone = flat high ——",ex:"Hold one steady high pitch. Think of singing 'ahhh' at the doctor." },
    { type:"translate",q:"Second tone (á) sounds like...",a:"Rising, like asking 'huh?'",o:["High and flat","Rising, like asking 'huh?'","Falling sharply","Dipping low then rising"],ph:"2nd tone = rising ／",ex:"Sounds like the end of an English question: 'Really?'" },
    { type:"translate",q:"Third tone (ǎ) sounds like...",a:"Dips low then rises",o:["High and flat","Rising","Falling sharply","Dips low then rises"],ph:"3rd tone = dip-rise ∨",ex:"Drops to the bottom of your range then bounces up. The trickiest tone." },
    { type:"translate",q:"Fourth tone (à) sounds like...",a:"Sharp falling, like saying 'No!'",o:["High and flat","Rising","Sharp falling, like saying 'No!'","Dipping then rising"],ph:"4th tone = falling ＼",ex:"Short and decisive. Like an angry 'No!' or 'Stop!'" },
    { type:"fillblank",q:"'Mā' means mother. 'Mǎ' means _____.",a:"horse",o:["mom","horse","scold","what"],ph:"mǎ = horse (3rd tone)",ex:"This is why tones matter. Wrong tone = completely different word." },
    { type:"translate",q:"'X' in pinyin sounds like...",a:"'sh' but with tongue near teeth",o:["English 'x'","'sh' but with tongue near teeth","'z' sound","'ks' sound"],ph:"x = hsee/shee (soft)",ex:"'Xie' = shee-eh. Tongue is near the front teeth, not curled back." },
    { type:"translate",q:"'Q' in pinyin sounds like...",a:"'ch' but lighter and near teeth",o:["English 'kw'","'ch' but lighter and near teeth","English 'k'","English 'g'"],ph:"q = chee (light)",ex:"'Qī' = chee. Similar to 'ch' but softer and more forward." },
    { type:"translate",q:"'Zh' in pinyin sounds like...",a:"'j' as in 'judge' but tongue curled back",o:["'z' as in 'zoo'","'j' as in 'judge' but tongue curled back","'sh' as in 'ship'","'ch' as in 'church'"],ph:"zh = jr (retroflex)",ex:"'Zhōngguó' (China) = joong-gwoh. Tongue curls back." },
    { type:"fillblank",q:"'C' in pinyin sounds like _____ in English.",a:"'ts' as in 'cats'",o:["'k'","'s'","'ts' as in 'cats'","'ch'"],ph:"c = ts",ex:"'Cài' (vegetable) = tsai. Never a 'k' sound." },
    { type:"translate",q:"'R' in pinyin sounds like...",a:"Between English 'r' and French 'j'",o:["Same as English 'r'","Between English 'r' and French 'j'","Rolled like Spanish 'r'","Silent"],ph:"r = rzh (soft)",ex:"'Rén' (person) = somewhere between 'ren' and 'zhen'." },
    { type:"translate",q:"The 'ü' sound (as in 'lǜ') is like...",a:"Say 'ee' with rounded lips",o:["'oo' as in 'food'","Say 'ee' with rounded lips","'uh' as in 'up'","'you'"],ph:"ü = ee with round lips",ex:"Only appears after j, q, x, l, n. Written as 'u' after j, q, x." },
    { type:"fillblank",q:"In Mandarin, the basic word order is _____.",a:"Subject-Verb-Object",o:["Subject-Object-Verb","Verb-Subject-Object","Subject-Verb-Object","Object-Subject-Verb"],ph:"n/a",ex:"'Wǒ chī fàn' = I eat rice. Same order as English! Good news." },
    { type:"translate",q:"Chinese characters are...",a:"Logograms (each represents a word/concept)",o:["Letters of an alphabet","Logograms (each represents a word/concept)","Syllabic symbols","Random drawings"],ph:"n/a",ex:"No alphabet. Each character = one syllable = one meaning. ~3,000 for daily use." },
    { type:"scenario",q:"You see '你好'. The pinyin is:",a:"nǐ hǎo",o:["ní háo","nǐ hǎo","nì hào","nī hāo"],ph:"nee how (both 3rd tone)",ex:"'Nǐ' = you (3rd tone). 'Hǎo' = good (3rd tone). The first word everyone learns." },
    { type:"translate",q:"'Sh' vs 'X' in pinyin:",a:"Sh = tongue curled back, X = tongue near teeth",o:["They sound the same","Sh = tongue curled back, X = tongue near teeth","Sh is softer","X is louder"],ph:"sh = retroflex, x = alveolar",ex:"'Shì' (is) vs 'Xǐ' (wash). The tongue position changes everything." },
    { type:"fillblank",q:"Two 3rd tones in a row: the first one changes to _____.",a:"2nd tone",o:["1st tone","2nd tone","4th tone","stays 3rd"],ph:"3 + 3 → 2 + 3",ex:"'Nǐ hǎo' is actually pronounced 'ní hǎo'. Tone sandhi rule." },
    { type:"translate",q:"'Zi', 'ci', 'si' — the 'i' sounds like...",a:"A buzzing 'zz' sound (not 'ee')",o:["'ee' as in 'see'","A buzzing 'zz' sound (not 'ee')","'ih' as in 'it'","Silent"],ph:"zi = dzz, ci = tss, si = ss",ex:"Special 'i' after z, c, s, zh, ch, sh, r. It's a buzzing continuation." },
    { type:"scenario",q:"Your friend says 'wǒ' — which tone?",a:"3rd tone (dip then rise)",o:["1st (flat)","2nd (rising)","3rd tone (dip then rise)","4th (falling)"],ph:"wǒ = 3rd tone",ex:"'Wǒ' = I/me. One of the first characters to learn: 我." },
    { type:"translate",q:"'Yī' can change tones depending on...",a:"The tone of the next word",o:["Nothing, it's always 1st tone","The tone of the next word","The speaker's mood","The time of day"],ph:"yī → yí or yì",ex:"Before 4th tone: yí. Before 1st/2nd/3rd: yì. One of Chinese's fun rules." },
  ],
  1: [
    { type:"translate",q:"Hello",a:"你好 (Nǐ hǎo)",o:["你好 (Nǐ hǎo)","再见 (Zàijiàn)","谢谢 (Xièxie)","好的 (Hǎo de)"],ph:"nee how",ex:"Literally 'you good'. The universal greeting." },
    { type:"translate",q:"Thank you",a:"谢谢 (Xièxie)",o:["不客气 (Bú kèqi)","请 (Qǐng)","谢谢 (Xièxie)","对不起 (Duìbuqǐ)"],ph:"shee-eh shee-eh",ex:"Repeated character for emphasis. Very common pattern in Chinese." },
    { type:"translate",q:"Goodbye",a:"再见 (Zàijiàn)",o:["你好 (Nǐ hǎo)","谢谢 (Xièxie)","再见 (Zàijiàn)","晚安 (Wǎn'ān)"],ph:"zai jee-en",ex:"'Zài' = again, 'jiàn' = see. 'See you again.'" },
    { type:"fillblank",q:"_____ 好! (Hello, formal/respectful)",a:"您 (Nín)",o:["你 (Nǐ)","您 (Nín)","他 (Tā)","我 (Wǒ)"],ph:"NEEN how",ex:"'Nín' = polite 'you'. Use with elders, strangers, in service." },
    { type:"translate",q:"Good morning",a:"早上好 (Zǎoshang hǎo)",o:["晚上好 (Wǎnshang hǎo)","早上好 (Zǎoshang hǎo)","下午好 (Xiàwǔ hǎo)","你好 (Nǐ hǎo)"],ph:"zow shahng how",ex:"'Zǎoshang' = morning. Add '好' (good) to any time of day." },
    { type:"scenario",q:"You walk into a restaurant. What do you say?",a:"你好! (Nǐ hǎo!)",o:["再见!","你好!","谢谢!","对不起!"],ph:"nee how",ex:"Universal greeting. Works everywhere, anytime." },
    { type:"translate",q:"You're welcome",a:"不客气 (Bú kèqi)",o:["谢谢 (Xièxie)","不客气 (Bú kèqi)","请 (Qǐng)","没关系 (Méi guānxi)"],ph:"boo kuh-chee",ex:"Literally 'no need to be polite'. Standard response to thanks." },
    { type:"translate",q:"Please",a:"请 (Qǐng)",o:["谢谢","不客气","对不起","请 (Qǐng)"],ph:"ching",ex:"Also means 'to invite/request'. 'Qǐng jìn' = please come in." },
    { type:"fillblank",q:"我 _____ 小明。(My name is Xiaoming)",a:"叫 (jiào)",o:["是 (shì)","叫 (jiào)","有 (yǒu)","去 (qù)"],ph:"woh jee-ow",ex:"'Jiào' = to be called. 'Wǒ jiào...' = I'm called..." },
    { type:"scenario",q:"Someone gives you a gift. You say:",a:"谢谢! (Xièxie!)",o:["对不起!","谢谢!","你好!","再见!"],ph:"shee-eh shee-eh",ex:"Always thank with 谢谢. Add '你' (nǐ) for emphasis: 谢谢你." },
    { type:"translate",q:"I'm sorry",a:"对不起 (Duìbuqǐ)",o:["对不起 (Duìbuqǐ)","不好意思 (Bù hǎoyìsi)","没关系 (Méi guānxi)","谢谢 (Xièxie)"],ph:"dway boo chee",ex:"For genuine apologies. 'Bù hǎoyìsi' = excuse me (lighter)." },
    { type:"translate",q:"It's okay / No problem",a:"没关系 (Méi guānxi)",o:["不客气","没关系 (Méi guānxi)","好的","可以"],ph:"may gwahn-shee",ex:"Literally 'no relationship/connection'. Very common response." },
    { type:"translate",q:"Yes (correct)",a:"对 (Duì)",o:["对 (Duì)","好 (Hǎo)","是 (Shì)","不 (Bù)"],ph:"dway",ex:"'Duì' = correct/right. Chinese doesn't have a single word for 'yes'." },
    { type:"fillblank",q:"你好 _____? (How are you?)",a:"吗 (ma)",o:["吧 (ba)","吗 (ma)","呢 (ne)","了 (le)"],ph:"nee how MAH",ex:"Adding '吗' turns any statement into a yes/no question." },
    { type:"scenario",q:"It's 9pm. Greet someone:",a:"晚上好! (Wǎnshang hǎo!)",o:["早上好!","下午好!","晚上好!","你好!"],ph:"wahn shahng how",ex:"'Wǎnshang' = evening. Used after about 6pm." },
    { type:"translate",q:"I don't understand",a:"我不懂 (Wǒ bù dǒng)",o:["我不知道","我不懂 (Wǒ bù dǒng)","我不会","我不要"],ph:"woh boo doong",ex:"'Dǒng' = understand. 'Bù' = not. Essential survival phrase." },
    { type:"translate",q:"Nice to meet you",a:"很高兴认识你 (Hěn gāoxìng rènshi nǐ)",o:["你好","很高兴认识你","再见","谢谢你"],ph:"hen gow-shing ren-shuh nee",ex:"'Gāoxìng' = happy. 'Rènshi' = to know/meet." },
    { type:"fillblank",q:"我很 _____，谢谢。(I'm very well, thank you.)",a:"好 (hǎo)",o:["大 (dà)","好 (hǎo)","多 (duō)","忙 (máng)"],ph:"woh hen HOW",ex:"'Hěn hǎo' = very good. 'Hěn' often softens to just 'pretty/quite'." },
    { type:"translate",q:"Excuse me (to get attention)",a:"不好意思 (Bù hǎoyìsi)",o:["对不起","不好意思 (Bù hǎoyìsi)","请问","劳驾"],ph:"boo how-ee-suh",ex:"Lighter than 'duìbuqǐ'. For bumping into someone or getting attention." },
    { type:"scenario",q:"Meet someone new:",a:"你好! 我叫... 很高兴认识你!",o:["再见!","你好! 我叫... 很高兴认识你!","晚安!","谢谢你!"],ph:"nee how, woh jee-ow...",ex:"Greeting + name + pleased to meet you. The Chinese trifecta." },
  ],
  2: [
    { type:"translate",q:"Water",a:"水 (Shuǐ)",o:["牛奶 (Niúnǎi)","水 (Shuǐ)","果汁 (Guǒzhī)","咖啡 (Kāfēi)"],ph:"shway",ex:"One of the most common characters. 'Hot water' = 热水 (rè shuǐ)." },
    { type:"translate",q:"Rice (cooked)",a:"米饭 (Mǐfàn)",o:["面包 (Miànbāo)","米饭 (Mǐfàn)","鸡肉 (Jīròu)","面条 (Miàntiáo)"],ph:"mee fahn",ex:"'Mǐ' = rice grain. 'Fàn' = cooked rice/meal. 'Chī fàn' = eat a meal." },
    { type:"fillblank",q:"我要一杯 _____。(I want a cup of coffee.)",a:"咖啡 (kāfēi)",o:["水 (shuǐ)","茶 (chá)","咖啡 (kāfēi)","牛奶 (niúnǎi)"],ph:"woh yow ee bay kah-fay",ex:"'Yào' = want. 'Bēi' = cup (measure word for drinks)." },
    { type:"scenario",q:"Order a beer:",a:"一瓶啤酒 (Yì píng píjiǔ)",o:["一杯咖啡","一瓶啤酒","一杯水","买单"],ph:"ee ping pee-jee-oh",ex:"'Píng' = bottle (measure word). 'Píjiǔ' = beer." },
    { type:"translate",q:"I'm hungry",a:"我饿了 (Wǒ è le)",o:["我累了","我饿了 (Wǒ è le)","我渴了","我要吃"],ph:"woh uh luh",ex:"'È' = hungry. '了' (le) indicates a change of state — I've become hungry." },
    { type:"translate",q:"Breakfast",a:"早餐 (Zǎocān)",o:["午餐 (Wǔcān)","早餐 (Zǎocān)","晚餐 (Wǎncān)","小吃 (Xiǎochī)"],ph:"zow tsahn",ex:"'Zǎo' = early/morning. 'Cān' = meal." },
    { type:"translate",q:"Chicken",a:"鸡肉 (Jīròu)",o:["猪肉 (Zhūròu)","鸡肉 (Jīròu)","牛肉 (Niúròu)","鱼 (Yú)"],ph:"jee roh",ex:"'Jī' = chicken. 'Ròu' = meat. Pattern: animal + 肉 = that meat." },
    { type:"fillblank",q:"这个菜很 _____。(This dish is very spicy.)",a:"辣 (là)",o:["冷 (lěng)","辣 (là)","大 (dà)","好 (hǎo)"],ph:"zhay guh tsai hen LAH",ex:"'Là' = spicy. Chinese cuisine takes spice seriously." },
    { type:"scenario",q:"Ask for the check:",a:"买单 (Mǎidān)",o:["菜单 (Càidān)","买单 (Mǎidān)","加水 (Jiā shuǐ)","再来 (Zài lái)"],ph:"my dahn",ex:"'Mǎi' = buy, 'dān' = bill. Also '结账 (jiézhàng)' in formal settings." },
    { type:"translate",q:"Delicious",a:"好吃 (Hǎochī)",o:["热 (Rè)","冷 (Lěng)","好吃 (Hǎochī)","辣 (Là)"],ph:"how chuh",ex:"'Hǎo' = good, 'chī' = eat. Literally 'good to eat'." },
    { type:"translate",q:"I'm thirsty",a:"我渴了 (Wǒ kě le)",o:["我饿了","我渴了 (Wǒ kě le)","我累了","我要喝"],ph:"woh kuh luh",ex:"'Kě' = thirsty. Same '了' pattern as hungry." },
    { type:"fillblank",q:"我想 _____ 这个。(I'd like to order this.)",a:"点 (diǎn)",o:["吃 (chī)","点 (diǎn)","喝 (hē)","做 (zuò)"],ph:"woh shee-ahng dee-en zhay guh",ex:"'Diǎn' = to order (food). 'Diǎn cài' = order dishes." },
    { type:"translate",q:"The menu",a:"菜单 (Càidān)",o:["买单 (Mǎidān)","菜单 (Càidān)","盘子 (Pánzi)","杯子 (Bēizi)"],ph:"tsai dahn",ex:"'Cài' = dish/vegetable. 'Dān' = list. The dish list." },
    { type:"scenario",q:"Say you don't eat pork:",a:"我不吃猪肉 (Wǒ bù chī zhūròu)",o:["我不饿","我不吃猪肉","我不要甜点","我不喝酒"],ph:"woh boo chuh joo roh",ex:"'Zhū' = pig. 'Ròu' = meat. Direct and clear." },
    { type:"translate",q:"Tea",a:"茶 (Chá)",o:["咖啡 (Kāfēi)","茶 (Chá)","水 (Shuǐ)","酒 (Jiǔ)"],ph:"chah",ex:"Tea is central to Chinese culture. Free tea at most restaurants." },
    { type:"translate",q:"Noodles",a:"面条 (Miàntiáo)",o:["米饭 (Mǐfàn)","面条 (Miàntiáo)","饺子 (Jiǎozi)","包子 (Bāozi)"],ph:"mee-en tee-ow",ex:"'Miàn' = noodle/flour. 'Tiáo' = strip (measure word)." },
    { type:"fillblank",q:"这个 _____ 多少钱？(How much is this dish?)",a:"菜 (cài)",o:["人 (rén)","菜 (cài)","水 (shuǐ)","桌 (zhuō)"],ph:"zhay guh TSAI dwoh-shaow chee-en",ex:"'Duōshao qián' = how much money. Essential shopping phrase." },
    { type:"translate",q:"Dumplings",a:"饺子 (Jiǎozi)",o:["包子 (Bāozi)","饺子 (Jiǎozi)","馒头 (Mántou)","汤 (Tāng)"],ph:"jee-ow-dzuh",ex:"The iconic Chinese food. Boiled, steamed, or fried." },
    { type:"scenario",q:"Compliment the food:",a:"很好吃! (Hěn hǎochī!)",o:["还好","很好吃!","我饿了","再来一个"],ph:"hen how chuh",ex:"'Hěn' = very. 'Hǎochī' = delicious. Simple and effective." },
    { type:"translate",q:"Too spicy",a:"太辣了 (Tài là le)",o:["很好吃","太辣了 (Tài là le)","不够辣","很热"],ph:"tai lah luh",ex:"'Tài...le' = too... Pattern: 太 + adjective + 了." },
  ],
  3: [
    { type:"translate",q:"One",a:"一 (Yī)",o:["一 (Yī)","二 (Èr)","三 (Sān)","十 (Shí)"],ph:"ee",ex:"Basic numbers: yī, èr, sān, sì, wǔ, liù, qī, bā, jiǔ, shí." },
    { type:"translate",q:"Twenty",a:"二十 (Èrshí)",o:["十二 (Shí'èr)","十五 (Shíwǔ)","二十 (Èrshí)","三十 (Sānshí)"],ph:"ar-shuh",ex:"Chinese numbers are logical: 二十 = two-ten = 20." },
    { type:"translate",q:"One hundred",a:"一百 (Yì bǎi)",o:["十 (Shí)","一千 (Yì qiān)","一百 (Yì bǎi)","五十 (Wǔshí)"],ph:"ee-bye",ex:"'Bǎi' = hundred. '一百' = one hundred." },
    { type:"fillblank",q:"我 _____ 岁。(I'm 35 years old.)",a:"三十五 (sānshí wǔ)",o:["二十五 (èrshí wǔ)","三十五 (sānshí wǔ)","四十 (sìshí)","十五 (shíwǔ)"],ph:"sahn-shuh woo SWAY",ex:"'Suì' = years old. Chinese math: 三十五 = three-ten-five = 35." },
    { type:"translate",q:"How much (money)?",a:"多少钱 (Duōshao qián)?",o:["几点了?","多少钱?","在哪里?","有多少?"],ph:"dwoh-shaow chee-en",ex:"'Duōshao' = how many/much. 'Qián' = money." },
    { type:"fillblank",q:"_____ 块钱。($50)",a:"五十 (wǔshí)",o:["十五 (shíwǔ)","五十 (wǔshí)","五百 (wǔbǎi)","五 (wǔ)"],ph:"woo-shuh kwai chee-en",ex:"'Kuài' = colloquial for yuan (Chinese dollar). 'Yuán' is formal." },
    { type:"translate",q:"First",a:"第一 (Dì yī)",o:["第二 (Dì èr)","第一 (Dì yī)","最后 (Zuìhòu)","第三 (Dì sān)"],ph:"dee ee",ex:"'Dì' + number = ordinal. Dì yī = first, dì èr = second." },
    { type:"scenario",q:"Say 'five, five, five':",a:"五，五，五 (Wǔ, wǔ, wǔ)",o:["三，三，三","五，五，五","六，六，六","一，一，一"],ph:"woo, woo, woo",ex:"Phone numbers said digit by digit. '一' often said as 'yāo' on phones." },
    { type:"translate",q:"Half",a:"半 (Bàn)",o:["全 (Quán)","半 (Bàn)","双 (Shuāng)","少 (Shǎo)"],ph:"bahn",ex:"'Bàn' = half. '半个小时' = half an hour." },
    { type:"fillblank",q:"我需要 _____ 分钟。(I need 10 minutes.)",a:"十 (shí)",o:["两 (liǎng)","五 (wǔ)","十 (shí)","二十 (èrshí)"],ph:"shuh fun-joong",ex:"'Fēnzhōng' = minutes. 'Shí fēnzhōng' = 10 minutes." },
    { type:"translate",q:"Fifteen",a:"十五 (Shíwǔ)",o:["五 (Wǔ)","十五 (Shíwǔ)","五十 (Wǔshí)","五百 (Wǔbǎi)"],ph:"shuh-woo",ex:"10+5 = 十五. Chinese number logic is beautifully simple." },
    { type:"translate",q:"One thousand",a:"一千 (Yì qiān)",o:["一百 (Yì bǎi)","一千 (Yì qiān)","一万 (Yí wàn)","一百万 (Yì bǎi wàn)"],ph:"ee chee-en",ex:"'Qiān' = thousand. Chinese also has '万 (wàn)' = 10,000." },
    { type:"fillblank",q:"这里有 _____ 个人。(There are 12 people here.)",a:"十二 (shí'èr)",o:["两 (liǎng)","十 (shí)","十二 (shí'èr)","二十 (èrshí)"],ph:"shuh-ar guh ren",ex:"'Gè' = general measure word for people and things." },
    { type:"scenario",q:"Ask how many people:",a:"有多少人? (Yǒu duōshao rén?)",o:["在哪里?","有多少人?","多少钱?","谁?"],ph:"yo dwoh-shaow ren",ex:"'Yǒu' = have/there are. 'Rén' = people." },
    { type:"translate",q:"Forty",a:"四十 (Sìshí)",o:["十四 (Shísì)","四十 (Sìshí)","四百 (Sìbǎi)","五十 (Wǔshí)"],ph:"suh-shuh",ex:"Shísì=14, Sìshí=40, Sìbǎi=400." },
    { type:"translate",q:"Zero",a:"零 (Líng)",o:["一 (Yī)","没 (Méi)","零 (Líng)","无 (Wú)"],ph:"ling",ex:"Used between numbers: 101 = 一百零一 (yì bǎi líng yī)." },
    { type:"scenario",q:"Tell a taxi: address number 1500:",a:"一千五百号 (Yì qiān wǔ bǎi hào)",o:["十五号","一百五十号","一千五百号","五百号"],ph:"ee chee-en woo-bye how",ex:"'Hào' = number (for addresses)." },
    { type:"translate",q:"Third",a:"第三 (Dì sān)",o:["第一 (Dì yī)","第二 (Dì èr)","第三 (Dì sān)","第四 (Dì sì)"],ph:"dee sahn",ex:"Pattern: 第 + number = ordinal." },
    { type:"fillblank",q:"我们团队有 _____ 个人。(Our team has 6 people.)",a:"六 (liù)",o:["三 (sān)","五 (wǔ)","六 (liù)","七 (qī)"],ph:"lee-oh guh ren",ex:"'Liù' = 6. 'Qī' = 7." },
    { type:"fillblank",q:"我的地址是 _____ 号。(My address is number 200.)",a:"两百 (liǎng bǎi)",o:["二十 (èrshí)","两百 (liǎng bǎi)","两千 (liǎng qiān)","十二 (shí'èr)"],ph:"lee-ahng bye how",ex:"'Liǎng' is used instead of 'èr' before measure words. 200 = 两百, not 二百." },
  ],
  // Levels 4-9 follow same pattern
  4: [
    { type:"translate",q:"Where is...?",a:"...在哪里? (Zài nǎlǐ?)",o:["怎么样?","在哪里?","是什么?","什么时候?"],ph:"zai nah-lee",ex:"'Zài' = at/in. 'Nǎlǐ' = where." },
    { type:"translate",q:"Turn left",a:"左转 (Zuǒ zhuǎn)",o:["直走 (Zhí zǒu)","左转 (Zuǒ zhuǎn)","右转 (Yòu zhuǎn)","停这里 (Tíng zhèlǐ)"],ph:"zwoh jwahn",ex:"'Zuǒ' = left. 'Yòu' = right. 'Zhuǎn' = turn." },
    { type:"fillblank",q:"餐厅在 _____。(The restaurant is on the right.)",a:"右边 (yòubiān)",o:["上面 (shàngmiàn)","下面 (xiàmiàn)","右边 (yòubiān)","远 (yuǎn)"],ph:"yoh bee-en",ex:"'Biān' = side. '左边' = left side, '右边' = right side." },
    { type:"scenario",q:"Ask where the subway is:",a:"请问，地铁站在哪里?",o:["几点了?","请问，地铁站在哪里?","我想去公园","出租车多少钱?"],ph:"ching-wen, dee-tee-eh jahn zai nah-lee",ex:"'Qǐngwèn' = may I ask (polite). 'Dìtiě zhàn' = subway station." },
    { type:"translate",q:"Go straight",a:"直走 (Zhí zǒu)",o:["转弯 (Zhuǎnwān)","直走 (Zhí zǒu)","停 (Tíng)","回去 (Huíqù)"],ph:"juh dzoh",ex:"'Zhí' = straight. 'Zǒu' = walk/go." },
    { type:"translate",q:"Near / Far",a:"近 / 远 (Jìn / Yuǎn)",o:["大 / 小","近 / 远","上 / 下","这 / 那"],ph:"jeen / yoo-en",ex:"'Hěn jìn' = very near. 'Hěn yuǎn' = very far." },
    { type:"fillblank",q:"我 _____ 打车。(I need to take a taxi.)",a:"需要 (xūyào)",o:["想要 (xiǎngyào)","需要 (xūyào)","有 (yǒu)","是 (shì)"],ph:"shoo-yow dah chuh",ex:"'Xūyào' = need. 'Dǎchē' = take a taxi." },
    { type:"translate",q:"The store",a:"商店 (Shāngdiàn)",o:["家 (Jiā)","商店 (Shāngdiàn)","学校 (Xuéxiào)","医院 (Yīyuàn)"],ph:"shahng dee-en",ex:"'Shāng' = business. 'Diàn' = shop/store." },
    { type:"scenario",q:"Tell a taxi to stop here:",a:"在这里停 (Zài zhèlǐ tíng)",o:["快点","在这里停","直走","左转"],ph:"zai zhuh-lee ting",ex:"'Tíng' = stop. 'Zhèlǐ' = here." },
    { type:"translate",q:"Street",a:"街 (Jiē)",o:["公园 (Gōngyuán)","街 (Jiē)","楼 (Lóu)","广场 (Guǎngchǎng)"],ph:"jee-eh",ex:"'Jiē' = street. 'Lù' (路) also means road/street." },
    { type:"fillblank",q:"_____ 这里远吗? (Is it far from here?)",a:"离 (Lí)",o:["在 (Zài)","离 (Lí)","有 (Yǒu)","去 (Qù)"],ph:"lee zhuh-lee yoo-en mah",ex:"'Lí' = from (distance). 'Lí zhèlǐ' = from here." },
    { type:"translate",q:"Behind",a:"后面 (Hòumiàn)",o:["前面 (Qiánmiàn)","后面 (Hòumiàn)","上面 (Shàngmiàn)","下面 (Xiàmiàn)"],ph:"hoh mee-en",ex:"'Hòu' = behind/back. 'Qián' = front." },
    { type:"scenario",q:"Ask how far the airport is:",a:"机场离这里远吗?",o:["飞机在哪?","机场离这里远吗?","机票多少钱?","几点的飞机?"],ph:"jee-chahng lee zhuh-lee yoo-en mah",ex:"'Jīchǎng' = airport. Pattern: place + 离这里 + 远吗?" },
    { type:"translate",q:"Next to",a:"旁边 (Pángbiān)",o:["上面 (Shàngmiàn)","旁边 (Pángbiān)","下面 (Xiàmiàn)","远 (Yuǎn)"],ph:"pahng bee-en",ex:"'Zài...pángbiān' = next to..." },
    { type:"fillblank",q:"银行在药店 _____。(The bank is across from the pharmacy.)",a:"对面 (duìmiàn)",o:["里面 (lǐmiàn)","对面 (duìmiàn)","上面 (shàngmiàn)","下面 (xiàmiàn)"],ph:"dway mee-en",ex:"'Duìmiàn' = opposite/across from." },
    { type:"translate",q:"Corner",a:"拐角 (Guǎijiǎo)",o:["街 (Jiē)","拐角 (Guǎijiǎo)","路口 (Lùkǒu)","大道 (Dàdào)"],ph:"gwai jee-ow",ex:"'Lùkǒu' = intersection, also commonly used." },
    { type:"scenario",q:"Ask someone to repeat:",a:"请再说一遍 (Qǐng zài shuō yí biàn)",o:["慢一点","请再说一遍","我不懂","大声一点"],ph:"ching zai shwoh ee bee-en",ex:"'Zài' = again. 'Shuō' = say. 'Yí biàn' = one time." },
    { type:"translate",q:"Intersection",a:"路口 (Lùkǒu)",o:["街 (Jiē)","路口 (Lùkǒu)","小区 (Xiǎoqū)","大道 (Dàdào)"],ph:"loo-koh",ex:"'Lù' = road. 'Kǒu' = mouth/opening. Road opening = intersection." },
    { type:"fillblank",q:"往前走两个 _____。(Walk two more blocks.)",a:"路口 (lùkǒu)",o:["街 (jiē)","路口 (lùkǒu)","米 (mǐ)","步 (bù)"],ph:"wahng chee-en dzoh lee-ahng guh loo-koh",ex:"Chinese directions often use intersections as landmarks." },
    { type:"translate",q:"In front of",a:"前面 (Qiánmiàn)",o:["后面 (Hòumiàn)","前面 (Qiánmiàn)","旁边 (Pángbiān)","远 (Yuǎn)"],ph:"chee-en mee-en",ex:"'Qián' = front. 'Qiánmiàn' = in front." },
  ],
  5: [
    { type:"translate",q:"I work in government",a:"我在政府工作 (Wǒ zài zhèngfǔ gōngzuò)",o:["我在政府工作","我在大学学习","我住在城市","我去办公室"],ph:"woh zai zhung-foo goong-zwoh",ex:"'Zhèngfǔ' = government. 'Gōngzuò' = work." },
    { type:"fillblank",q:"我是项目 _____。(I'm a project manager.)",a:"经理 (jīnglǐ)",o:["医生 (yīshēng)","经理 (jīnglǐ)","老师 (lǎoshī)","律师 (lǜshī)"],ph:"jing-lee",ex:"'Jīnglǐ' = manager. Very common professional title." },
    { type:"translate",q:"Meeting",a:"会议 (Huìyì)",o:["办公室 (Bàngōngshì)","会议 (Huìyì)","项目 (Xiàngmù)","团队 (Tuánduì)"],ph:"hway-ee",ex:"'Kāi huì' = have a meeting (literally 'open a meeting')." },
    { type:"translate",q:"Team",a:"团队 (Tuánduì)",o:["小组 (Xiǎozǔ)","团队 (Tuánduì)","老板 (Lǎobǎn)","工作 (Gōngzuò)"],ph:"twahn-dway",ex:"'Tuán' = group. 'Duì' = team." },
    { type:"scenario",q:"Introduce your job:",a:"我在政府做经理",o:["我是学生","我在政府做经理","我没有工作","我去上班"],ph:"woh zai zhung-foo zwoh jing-lee",ex:"'Zuò' = do/work as. Natural job introduction." },
    { type:"fillblank",q:"我三点有个 _____。(I have a meeting at 3.)",a:"会 (huì)",o:["饭 (fàn)","会 (huì)","课 (kè)","约 (yuē)"],ph:"hway",ex:"'Kāi huì' or just '有个会' = have a meeting." },
    { type:"translate",q:"Boss",a:"老板 (Lǎobǎn)",o:["朋友 (Péngyou)","老板 (Lǎobǎn)","同事 (Tóngshì)","客户 (Kèhù)"],ph:"low-bahn",ex:"Literally 'old board/boss'. Used widely, even for shop owners." },
    { type:"translate",q:"Project",a:"项目 (Xiàngmù)",o:["工作 (Gōngzuò)","办公室 (Bàngōngshì)","项目 (Xiàngmù)","问题 (Wèntí)"],ph:"shee-ahng-moo",ex:"Standard business Chinese." },
    { type:"fillblank",q:"我的团队有十九 _____ 人。(My team has 19 people.)",a:"个 (gè)",o:["位 (wèi)","个 (gè)","名 (míng)","只 (zhī)"],ph:"guh",ex:"'Gè' is the general measure word. Used for people, things, ideas." },
    { type:"scenario",q:"Say you're busy:",a:"我工作很忙 (Wǒ gōngzuò hěn máng)",o:["我没时间","我工作很忙","我回家了","我想休息"],ph:"woh goong-zwoh hen mahng",ex:"'Máng' = busy. Very commonly used." },
    { type:"translate",q:"Schedule",a:"日程 (Rìchéng)",o:["日历 (Rìlì)","日程 (Rìchéng)","钟 (Zhōng)","时间 (Shíjiān)"],ph:"ruh-chung",ex:"'Rì' = day. 'Chéng' = schedule/journey." },
    { type:"fillblank",q:"这个项目今天要 _____。(This project needs to be finished today.)",a:"完成 (wánchéng)",o:["开始 (kāishǐ)","完成 (wánchéng)","讨论 (tǎolùn)","取消 (qǔxiāo)"],ph:"wahn-chung",ex:"'Wánchéng' = complete/finish." },
    { type:"translate",q:"Email",a:"电子邮件 (Diànzǐ yóujiàn)",o:["消息 (Xiāoxi)","电子邮件 (Diànzǐ yóujiàn)","信 (Xìn)","电话 (Diànhuà)"],ph:"dee-en-dzuh yo-jee-en",ex:"Long word but common. Often shortened to '邮件' (yóujiàn)." },
    { type:"scenario",q:"Ask what time the meeting is:",a:"会议几点开? (Huìyì jǐ diǎn kāi?)",o:["会议在哪?","会议几点开?","谁来开会?","为什么开会?"],ph:"hway-ee jee dee-en kai",ex:"'Jǐ diǎn' = what time (what o'clock). 'Kāi' = start/open." },
    { type:"translate",q:"Coworker",a:"同事 (Tóngshì)",o:["朋友 (Péngyou)","同事 (Tóngshì)","老板 (Lǎobǎn)","员工 (Yuángōng)"],ph:"toong-shuh",ex:"'Tóng' = same. 'Shì' = matter/affair. Same-affair person." },
    { type:"fillblank",q:"我六点 _____。(I leave at 6.)",a:"下班 (xiàbān)",o:["吃饭 (chīfàn)","下班 (xiàbān)","睡觉 (shuìjiào)","到 (dào)"],ph:"shee-ah bahn",ex:"'Xiàbān' = get off work. 'Shàngbān' = start work." },
    { type:"translate",q:"Deadline",a:"截止日期 (Jiézhǐ rìqī)",o:["最后时间","截止日期 (Jiézhǐ rìqī)","最后一天","时间限制"],ph:"jee-eh-juh ruh-chee",ex:"'Jiézhǐ' = cut off. 'Rìqī' = date." },
    { type:"scenario",q:"Say you'll finish by Friday:",a:"我周五之前做完 (Wǒ zhōuwǔ zhīqián zuòwán)",o:["我明天做","我周五之前做完","我今天不行","我需要更多时间"],ph:"woh joh-woo juh-chee-en zwoh-wahn",ex:"'Zhīqián' = before. 'Zuòwán' = finish doing." },
    { type:"translate",q:"Salary",a:"工资 (Gōngzī)",o:["钱 (Qián)","工资 (Gōngzī)","付款 (Fùkuǎn)","账单 (Zhàngdān)"],ph:"goong-dzuh",ex:"'Gōng' = work. 'Zī' = resources. Work resources = salary." },
    { type:"fillblank",q:"我周一到周 _____ 上班。(I work Monday to Friday.)",a:"五 (wǔ)",o:["四 (sì)","五 (wǔ)","六 (liù)","日 (rì)"],ph:"woo",ex:"周一=Monday, 周二=Tuesday... 周五=Friday. Literally week-one through week-five." },
  ],
  6: [
    { type:"translate",q:"What time is it?",a:"几点了? (Jǐ diǎn le?)",o:["几点了?","今天星期几?","什么时候?","你好吗?"],ph:"jee dee-en luh",ex:"'Jǐ' = how many. 'Diǎn' = o'clock." },
    { type:"translate",q:"It's hot",a:"天气很热 (Tiānqì hěn rè)",o:["天气很冷","天气很热","下雨了","阴天"],ph:"tee-en-chee hen ruh",ex:"'Tiānqì' = weather. 'Rè' = hot." },
    { type:"fillblank",q:"今天是星期 _____。(Today is Tuesday.)",a:"二 (èr)",o:["一 (yī)","二 (èr)","六 (liù)","天 (tiān)"],ph:"shing-chee ar",ex:"星期一=Mon, 星期二=Tue... 星期天/日=Sunday." },
    { type:"translate",q:"Tomorrow",a:"明天 (Míngtiān)",o:["昨天 (Zuótiān)","今天 (Jīntiān)","明天 (Míngtiān)","现在 (Xiànzài)"],ph:"ming tee-en",ex:"'Míng' = bright. 'Tiān' = day. Bright day = tomorrow." },
    { type:"translate",q:"It's raining",a:"下雨了 (Xià yǔ le)",o:["出太阳了","下雨了","刮风了","下雪了"],ph:"shee-ah yoo luh",ex:"'Xià' = fall. 'Yǔ' = rain. Rain is falling." },
    { type:"fillblank",q:"现在 _____ 点。(It's 3 o'clock now.)",a:"三 (sān)",o:["两 (liǎng)","三 (sān)","五 (wǔ)","一 (yī)"],ph:"sahn dee-en",ex:"Time is simple: number + 点 (diǎn) = o'clock." },
    { type:"scenario",q:"Tell someone it's cold today:",a:"今天很冷 (Jīntiān hěn lěng)",o:["今天很热","今天很冷","今天天气好","今天不错"],ph:"jin-tee-en hen lung",ex:"'Lěng' = cold. Direct and simple." },
    { type:"translate",q:"Week",a:"星期 (Xīngqī)",o:["天 (Tiān)","月 (Yuè)","星期 (Xīngqī)","年 (Nián)"],ph:"shing-chee",ex:"Also '周 (zhōu)'. '这个星期' = this week." },
    { type:"translate",q:"Yesterday",a:"昨天 (Zuótiān)",o:["今天 (Jīntiān)","明天 (Míngtiān)","昨天 (Zuótiān)","现在 (Xiànzài)"],ph:"zwoh-tee-en",ex:"Zuótiān = yesterday. Jīntiān = today. Míngtiān = tomorrow." },
    { type:"fillblank",q:"上个 _____ 我去了公园。(Last Sunday I went to the park.)",a:"星期天 (xīngqītiān)",o:["一月 (yīyuè)","夏天 (xiàtiān)","星期天 (xīngqītiān)","年 (nián)"],ph:"shahng guh shing-chee-tee-en",ex:"'Shàng gè' = last (time period)." },
    { type:"translate",q:"Spring",a:"春天 (Chūntiān)",o:["夏天 (Xiàtiān)","春天 (Chūntiān)","秋天 (Qiūtiān)","冬天 (Dōngtiān)"],ph:"chwun tee-en",ex:"Seasons: 春天, 夏天, 秋天, 冬天." },
    { type:"fillblank",q:"外面风很 _____。(It's very windy outside.)",a:"大 (dà)",o:["热 (rè)","大 (dà)","多 (duō)","冷 (lěng)"],ph:"dah",ex:"Wind is described as 'big' in Chinese: 风很大 = wind very big." },
    { type:"scenario",q:"Ask if it will rain tomorrow:",a:"明天会下雨吗?",o:["明天冷吗?","明天会下雨吗?","几点了?","是夏天吗?"],ph:"ming-tee-en hway shee-ah yoo mah",ex:"'Huì' = will. '会下雨吗' = will it rain?" },
    { type:"translate",q:"Month",a:"月 (Yuè)",o:["天 (Tiān)","星期 (Xīngqī)","月 (Yuè)","年 (Nián)"],ph:"yoo-eh",ex:"Also means 'moon'. Months are just numbers: 一月=January, 二月=February." },
    { type:"translate",q:"It's sunny",a:"出太阳了 (Chū tàiyáng le)",o:["很热","出太阳了","天晴了","天气好"],ph:"choo tai-yahng luh",ex:"'Tàiyáng' = sun. 'Chū' = come out. The sun came out." },
    { type:"fillblank",q:"_____ 很热。(Summer is very hot.)",a:"夏天 (Xiàtiān)",o:["冬天 (Dōngtiān)","夏天 (Xiàtiān)","秋天 (Qiūtiān)","三月 (Sānyuè)"],ph:"shee-ah tee-en",ex:"'Xià' = below/summer. 'Tiān' = day/sky." },
    { type:"translate",q:"Cloudy",a:"阴天 (Yīntiān)",o:["晴天 (Qíngtiān)","阴天 (Yīntiān)","雨天 (Yǔtiān)","刮风 (Guāfēng)"],ph:"yin tee-en",ex:"'Yīn' = overcast/cloudy. 'Qíng' = clear/sunny." },
    { type:"scenario",q:"Say the weather is nice:",a:"今天天气很好 (Jīntiān tiānqì hěn hǎo)",o:["今天天气不好","今天天气很好","下雨了","今天很冷"],ph:"jin-tee-en tee-en-chee hen how",ex:"'Hǎo' = good. Simple and universally understood." },
    { type:"translate",q:"At night",a:"晚上 (Wǎnshang)",o:["早上 (Zǎoshang)","下午 (Xiàwǔ)","晚上 (Wǎnshang)","中午 (Zhōngwǔ)"],ph:"wahn-shahng",ex:"Times of day: 早上, 上午, 中午, 下午, 晚上." },
    { type:"fillblank",q:"我 _____ 不上班。(I don't work on Saturdays.)",a:"周六 (zhōuliù)",o:["周一 (zhōuyī)","周三 (zhōusān)","周五 (zhōuwǔ)","周六 (zhōuliù)"],ph:"joh-lee-oh",ex:"'Zhōuliù' = Saturday. Weekend = 周末 (zhōumò)." },
  ],
  7: [
    { type:"translate",q:"Mother",a:"妈妈 (Māma)",o:["爸爸 (Bàba)","妈妈 (Māma)","姐姐 (Jiějie)","奶奶 (Nǎinai)"],ph:"mah-mah",ex:"Doubled character = familiar/casual. '母亲 (mǔqīn)' is formal." },
    { type:"translate",q:"Brother (older)",a:"哥哥 (Gēge)",o:["弟弟 (Dìdi)","哥哥 (Gēge)","叔叔 (Shūshu)","儿子 (Érzi)"],ph:"guh-guh",ex:"Chinese distinguishes older (哥哥) from younger (弟弟) siblings." },
    { type:"fillblank",q:"我的 _____ 四岁了。(My nephew is 4 years old.)",a:"外甥 (wàishēng)",o:["哥哥 (gēge)","外甥 (wàishēng)","爷爷 (yéye)","爸爸 (bàba)"],ph:"why-shung",ex:"'Wàishēng' = nephew (sister's son). Family terms differ by maternal/paternal side." },
    { type:"translate",q:"Niece",a:"侄女 (Zhínǚ)",o:["表妹 (Biǎomèi)","侄女 (Zhínǚ)","女儿 (Nǚ'ér)","妹妹 (Mèimei)"],ph:"juh-nyoo",ex:"'Zhí' = brother's child. Chinese has different words for maternal vs paternal relatives." },
    { type:"scenario",q:"Tell someone about your pets:",a:"我有两只狗 (Wǒ yǒu liǎng zhī gǒu)",o:["我有一只猫","我有两只狗","我没有宠物","我想要一只鸟"],ph:"woh yo lee-ahng juh go",ex:"'Zhī' = measure word for animals. 'Gǒu' = dog." },
    { type:"translate",q:"Grandfather (paternal)",a:"爷爷 (Yéye)",o:["爸爸 (Bàba)","叔叔 (Shūshu)","爷爷 (Yéye)","舅舅 (Jiùjiu)"],ph:"yeh-yeh",ex:"Paternal grandpa = 爷爷. Maternal grandpa = 外公 (wàigōng) or 姥爷 (lǎoye)." },
    { type:"translate",q:"Wife / Husband",a:"妻子 / 丈夫 (Qīzi / Zhàngfu)",o:["女朋友 / 男朋友","妻子 / 丈夫","姐姐 / 哥哥","女儿 / 儿子"],ph:"chee-dzuh / jahng-foo",ex:"Casual: 老婆 (lǎopo) / 老公 (lǎogōng) — literally 'old wife/husband'." },
    { type:"translate",q:"Son / Daughter",a:"儿子 / 女儿 (Érzi / Nǚ'ér)",o:["侄子 / 侄女","儿子 / 女儿","孙子 / 孙女","外甥 / 外甥女"],ph:"ar-dzuh / nyoo-ar",ex:"'Ér' = son. 'Nǚ' = female/daughter." },
    { type:"scenario",q:"Say you have a big family:",a:"我家人很多 (Wǒ jiārén hěn duō)",o:["我家很小","我家人很多","我没有家人","我一个人住"],ph:"woh jee-ah-ren hen dwoh",ex:"'Jiārén' = family members. 'Duō' = many." },
    { type:"fillblank",q:"我 _____ 做饭很好吃。(My grandma cooks very well.)",a:"奶奶 (nǎinai)",o:["狗 (gǒu)","奶奶 (nǎinai)","车 (chē)","家 (jiā)"],ph:"nai-nai",ex:"'Nǎinai' = paternal grandma. 'Zuò fàn' = cook." },
    { type:"translate",q:"Cousin",a:"表哥 (Biǎogē)",o:["哥哥 (Gēge)","表哥 (Biǎogē)","叔叔 (Shūshu)","侄子 (Zhízi)"],ph:"bee-ow guh",ex:"Chinese has 8+ different words for cousin depending on maternal/paternal, older/younger, male/female." },
    { type:"translate",q:"Uncle (father's brother)",a:"叔叔 (Shūshu)",o:["爷爷 (Yéye)","表哥 (Biǎogē)","叔叔 (Shūshu)","爸爸 (Bàba)"],ph:"shoo-shoo",ex:"'Shūshu' = father's younger brother. Different word for older brother, mother's brother, etc." },
    { type:"fillblank",q:"我 _____ 住在德州。(My parents live in Texas.)",a:"父母 (fùmǔ)",o:["朋友 (péngyou)","父母 (fùmǔ)","狗 (gǒu)","老板 (lǎobǎn)"],ph:"foo-moo",ex:"'Fù' = father. 'Mǔ' = mother. '父母' = parents." },
    { type:"scenario",q:"Introduce your sister:",a:"这是我姐姐 (Zhè shì wǒ jiějie)",o:["这是我妈妈","这是我姐姐","这是我表妹","这是我朋友"],ph:"zhuh shuh woh jee-eh-jee-eh",ex:"'Zhè shì...' = this is... 'Jiějie' = older sister." },
    { type:"translate",q:"Grandchildren",a:"孙子 (Sūnzi)",o:["儿子 (Érzi)","侄子 (Zhízi)","孙子 (Sūnzi)","表弟 (Biǎodì)"],ph:"swun-dzuh",ex:"'Sūnzi' = grandson. 'Sūnnǚ' = granddaughter." },
    { type:"fillblank",q:"我们是一个很 _____ 的家庭。(We're a very close family.)",a:"亲密 (qīnmì)",o:["大 (dà)","亲密 (qīnmì)","好 (hǎo)","新 (xīn)"],ph:"chin-mee",ex:"'Qīnmì' = intimate/close. Describes family bonds." },
    { type:"translate",q:"Girlfriend / Boyfriend",a:"女朋友 / 男朋友 (Nǚ péngyou / Nán péngyou)",o:["妻子 / 丈夫","女朋友 / 男朋友","姐姐 / 哥哥","女人 / 男人"],ph:"nyoo pung-yo / nahn pung-yo",ex:"Literally 'female friend / male friend'. Context makes it clear." },
    { type:"scenario",q:"Say your nephew loves trucks:",a:"我外甥很喜欢卡车",o:["我外甥很大","我外甥很喜欢卡车","他四岁了","他和我住"],ph:"woh why-shung hen shee-hwahn kah-chuh",ex:"'Xǐhuan' = like. 'Kǎchē' = truck." },
    { type:"translate",q:"Twins",a:"双胞胎 (Shuāngbāotāi)",o:["兄弟 (Xiōngdì)","双胞胎 (Shuāngbāotāi)","表兄弟 (Biǎo xiōngdì)","朋友 (Péngyou)"],ph:"shwahng-bow-tai",ex:"'Shuāng' = double/pair. 'Bāotāi' = womb. Double womb." },
    { type:"fillblank",q:"我最喜欢的 _____ 是春节。(My favorite tradition is Spring Festival.)",a:"传统 (chuántǒng)",o:["食物 (shíwù)","传统 (chuántǒng)","节日 (jiérì)","家人 (jiārén)"],ph:"chwahn-toong",ex:"'Chuántǒng' = tradition. '春节 (Chūnjié)' = Chinese New Year / Spring Festival." },
  ],
  8: [
    { type:"translate",q:"To go",a:"去 (Qù)",o:["是 (Shì)","去 (Qù)","看 (Kàn)","给 (Gěi)"],ph:"choo",ex:"'Wǒ qù' = I go. No conjugation needed — Chinese verbs don't change!" },
    { type:"translate",q:"To want",a:"想要 (Xiǎng yào)",o:["可以 (Kěyǐ)","想要 (Xiǎng yào)","应该 (Yīnggāi)","知道 (Zhīdào)"],ph:"shee-ahng yow",ex:"'Xiǎng' = think/want. 'Yào' = want/need. Together = want to." },
    { type:"fillblank",q:"我 _____ 去餐厅。(I want to go to the restaurant.)",a:"想 (xiǎng)",o:["有 (yǒu)","想 (xiǎng)","能 (néng)","要 (yào)"],ph:"shee-ahng",ex:"'Xiǎng' + verb = want to do something." },
    { type:"translate",q:"To know (a fact)",a:"知道 (Zhīdào)",o:["认识 (Rènshi)","知道 (Zhīdào)","想 (Xiǎng)","相信 (Xiāngxìn)"],ph:"juh-dow",ex:"'Zhīdào' = know facts. 'Rènshi' = know people. Same as saber/conocer." },
    { type:"translate",q:"I can",a:"我能 (Wǒ néng)",o:["我想","我应该","我能 (Wǒ néng)","我知道"],ph:"woh nung",ex:"'Néng' = can (ability). '可以 (kěyǐ)' = can (permission)." },
    { type:"fillblank",q:"我们星期天 _____ 公园。(We go to the park on Sundays.)",a:"去 (qù)",o:["是 (shì)","去 (qù)","有 (yǒu)","做 (zuò)"],ph:"choo",ex:"Chinese verbs never change form. 'Qù' is always 'qù'." },
    { type:"translate",q:"To do / To make",a:"做 (Zuò)",o:["说 (Shuō)","做 (Zuò)","放 (Fàng)","有 (Yǒu)"],ph:"zwoh",ex:"'Nǐ zuò shénme?' = What are you doing?" },
    { type:"scenario",q:"Say 'I need to work':",a:"我需要工作 (Wǒ xūyào gōngzuò)",o:["我想工作","我需要工作","我能工作","我应该工作"],ph:"woh shoo-yow goong-zwoh",ex:"'Xūyào' = need. Stronger than 'xiǎng' (want)." },
    { type:"fillblank",q:"你 _____ 银行在哪里吗? (Do you know where the bank is?)",a:"知道 (zhīdào)",o:["认识 (rènshi)","知道 (zhīdào)","想 (xiǎng)","能 (néng)"],ph:"juh-dow",ex:"'Zhīdào' = know a fact/information." },
    { type:"translate",q:"To speak",a:"说 (Shuō)",o:["听 (Tīng)","说 (Shuō)","读 (Dú)","写 (Xiě)"],ph:"shwoh",ex:"'Shuō Zhōngwén' = speak Chinese." },
    { type:"translate",q:"To eat",a:"吃 (Chī)",o:["喝 (Hē)","吃 (Chī)","做饭 (Zuòfàn)","点菜 (Diǎncài)"],ph:"chuh",ex:"One of the most important verbs. 'Chī fàn' = eat a meal." },
    { type:"translate",q:"To sleep",a:"睡觉 (Shuìjiào)",o:["休息 (Xiūxi)","睡觉 (Shuìjiào)","做梦 (Zuòmèng)","起床 (Qǐchuáng)"],ph:"shway jee-ow",ex:"'Shuì' = sleep. 'Jiào' = nap/sleep." },
    { type:"fillblank",q:"她中文 _____ 得很好。(She speaks Chinese very well.)",a:"说 (shuō)",o:["知 (zhī)","说 (shuō)","有 (yǒu)","认 (rèn)"],ph:"shwoh",ex:"Pattern: verb + 得 (de) + how well. 'Shuō de hěn hǎo'." },
    { type:"scenario",q:"Say you don't understand:",a:"我不懂 (Wǒ bù dǒng)",o:["我不知道","我不懂","我不能","我不要"],ph:"woh boo doong",ex:"'Bù' = not. 'Dǒng' = understand. Your #1 survival phrase." },
    { type:"translate",q:"To give",a:"给 (Gěi)",o:["拿 (Ná)","给 (Gěi)","放 (Fàng)","带 (Dài)"],ph:"gay",ex:"'Gěi wǒ' = give me." },
    { type:"fillblank",q:"你 _____ 跟我一起去吗? (Can you go with me?)",a:"能 (néng)",o:["知 (zhī)","能 (néng)","想 (xiǎng)","要 (yào)"],ph:"nung",ex:"'Néng' = can (ability). 'Gēn wǒ yìqǐ' = with me together." },
    { type:"translate",q:"To leave",a:"走 (Zǒu)",o:["进 (Jìn)","走 (Zǒu)","到 (Dào)","回 (Huí)"],ph:"dzoh",ex:"'Wǒ zǒu le' = I'm leaving. '走' also means walk." },
    { type:"translate",q:"To bring",a:"带 (Dài)",o:["拿 (Ná)","带 (Dài)","给 (Gěi)","放 (Fàng)"],ph:"dai",ex:"'Dài' = bring/carry. 'Bǎ... dài lái' = bring something." },
    { type:"scenario",q:"Ask for help:",a:"你能帮我吗? (Nǐ néng bāng wǒ ma?)",o:["你能给我吗?","你能帮我吗?","你能告诉我吗?","你能带我吗?"],ph:"nee nung bahng woh mah",ex:"'Bāng' = help. 'Ma' turns it into a question." },
    { type:"fillblank",q:"我明天要早点 _____。(I need to leave early tomorrow.)",a:"走 (zǒu)",o:["睡 (shuì)","走 (zǒu)","吃 (chī)","工作 (gōngzuò)"],ph:"dzoh",ex:"'Zǎo diǎn' = a bit early. 'Zǒu' = leave/go." },
  ],
  9: [
    { type:"scenario",q:"Meet someone new:",a:"你好! 你叫什么名字?",o:["再见!","你好! 你叫什么名字?","多少钱?","我饿了"],ph:"nee how, nee jee-ow shummuh ming-dzuh",ex:"'Shénme míngzi' = what name. The standard introduction opener." },
    { type:"fillblank",q:"你是 _____ 人? (Where are you from?)",a:"哪里 (nǎlǐ)",o:["这里 (zhèlǐ)","哪里 (nǎlǐ)","那里 (nàlǐ)","多少 (duōshao)"],ph:"nah-lee",ex:"'Nǐ shì nǎlǐ rén?' = You are where person?" },
    { type:"scenario",q:"Someone asks what you do:",a:"我在政府做经理",o:["我不知道","我在政府做经理","我是学生","我不工作"],ph:"woh zai zhung-foo zwoh jing-lee",ex:"Clean professional introduction. Simple and direct." },
    { type:"translate",q:"I like it a lot",a:"我很喜欢 (Wǒ hěn xǐhuan)",o:["我很喜欢","我不喜欢","我很爱","还可以"],ph:"woh hen shee-hwahn",ex:"'Xǐhuan' = like. 'Ài' = love (stronger)." },
    { type:"fillblank",q:"你 _____ 这个菜吗? (Did you like this dish?)",a:"喜欢 (xǐhuan)",o:["要 (yào)","喜欢 (xǐhuan)","知道 (zhīdào)","看 (kàn)"],ph:"shee-hwahn",ex:"No past tense change needed. Context makes it clear." },
    { type:"scenario",q:"Find the bathroom:",a:"请问，洗手间在哪里?",o:["我需要水","请问，洗手间在哪里?","我想走了","我累了"],ph:"ching-wen, shee-show-jee-en zai nah-lee",ex:"'Xǐshǒujiān' = washroom (literally hand-washing room)." },
    { type:"translate",q:"See you later",a:"回头见 (Huítóu jiàn)",o:["再见","下次见","回头见","晚安"],ph:"hway-toe jee-en",ex:"Literally 'turn head see'. Casual farewell." },
    { type:"fillblank",q:"很高兴 _____ 你。(Nice to meet you.)",a:"认识 (rènshi)",o:["知道 (zhīdào)","认识 (rènshi)","看到 (kàndào)","遇到 (yùdào)"],ph:"ren-shuh",ex:"'Rènshi' = to know/become acquainted with." },
    { type:"scenario",q:"Ask for their number:",a:"能给我你的电话号码吗?",o:["你叫什么?","能给我你的电话号码吗?","你住哪里?","你有车吗?"],ph:"nung gay woh nee duh dee-en-hwah how-mah mah",ex:"'Diànhuà hàomǎ' = phone number." },
    { type:"translate",q:"Let's go!",a:"走吧! (Zǒu ba!)",o:["等一下!","走吧!","停!","快!"],ph:"dzoh bah",ex:"'Ba' softens the command. Makes it 'let's go' not 'go!'." },
    { type:"scenario",q:"Say you're learning Chinese:",a:"我在学中文 (Wǒ zài xué Zhōngwén)",o:["我会说中文","我在学中文","我不会中文","我会一点"],ph:"woh zai shoo-eh joong-wen",ex:"'Xué' = study/learn. 'Zhōngwén' = Chinese language." },
    { type:"fillblank",q:"我们去 _____ 点东西吧? (Let's go get a drink?)",a:"喝 (hē)",o:["做 (zuò)","喝 (hē)","看 (kàn)","给 (gěi)"],ph:"huh",ex:"'Hē' = drink. 'Hē diǎn dōngxi' = drink some things." },
    { type:"translate",q:"What do you think?",a:"你觉得呢? (Nǐ juéde ne?)",o:["你要什么?","你觉得呢?","你做什么?","你说什么?"],ph:"nee jweh-duh nuh",ex:"'Juéde' = feel/think. '呢' makes it conversational." },
    { type:"scenario",q:"Compliment someone's cooking:",a:"太好吃了! (Tài hǎochī le!)",o:["还行","太好吃了!","我饿了","再来一点"],ph:"tai how-chuh luh",ex:"'Tài...le' = too/so... 'So delicious!'" },
    { type:"translate",q:"I agree",a:"我同意 (Wǒ tóngyì)",o:["我觉得是","我同意","你说得对","当然"],ph:"woh toong-ee",ex:"'Tóngyì' = agree. Direct and clear." },
    { type:"fillblank",q:"昨晚我玩得很 _____。(I had a great time last night.)",a:"开心 (kāixīn)",o:["不好 (bùhǎo)","开心 (kāixīn)","大 (dà)","多 (duō)"],ph:"kai-shin",ex:"'Kāixīn' = happy/fun. 'Wán de hěn kāixīn' = played very happily." },
    { type:"scenario",q:"Say goodbye after a great time:",a:"今天很开心，谢谢!",o:["再见","今天很开心，谢谢!","晚安","明天见"],ph:"jin-tee-en hen kai-shin, shee-eh shee-eh",ex:"'Kāixīn' = happy. Warm and genuine farewell." },
    { type:"translate",q:"Of course!",a:"当然! (Dāngrán!)",o:["也许!","当然!","不知道!","谁知道!"],ph:"dahng-rahn",ex:"'Dāngrán' = of course/naturally. Strong agreement." },
    { type:"fillblank",q:"我们周末 _____ 吧。(Let's hang out this weekend.)",a:"出去玩 (chūqù wán)",o:["工作 (gōngzuò)","出去玩 (chūqù wán)","睡觉 (shuìjiào)","学习 (xuéxí)"],ph:"choo-choo wahn",ex:"'Chūqù wán' = go out and play/hang out." },
    { type:"scenario",q:"Invite someone to hang out:",a:"周末有空吗? (Zhōumò yǒu kòng ma?)",o:["你忙吗?","周末有空吗?","你要工作吗?","你住哪里?"],ph:"joh-moh yo koong mah",ex:"'Yǒu kòng' = have free time. The natural Chinese invitation." },
  ],
};
